//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Web.CommonRes", typeof(CommonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Internal Server Error.
        /// </summary>
        public static string ASPError_500 {
            get {
                return ResourceManager.GetString("ASPError_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, Duplicate Key is not allowed..
        /// </summary>
        public static string ASPError_DuplicateKey {
            get {
                return ResourceManager.GetString("ASPError_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code available.
        /// </summary>
        public static string ASPError_NoCodeAvailable {
            get {
                return ResourceManager.GetString("ASPError_NoCodeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Fields.
        /// </summary>
        public static string Control_ConfigurationClass_ActionInfoFieldsTitle {
            get {
                return ResourceManager.GetString("Control_ConfigurationClass_ActionInfoFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be uploaded.  Maximum file size limit is {0} MB..
        /// </summary>
        public static string Control_DocEditControl_ReachMaximumFileSize {
            get {
                return ResourceManager.GetString("Control_DocEditControl_ReachMaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be uploaded.  ScriptUtils.ASPForm component has problem, please try again..
        /// </summary>
        public static string Control_DocEditControl_ScriptUtilsASPFormUploadFail {
            get {
                return ResourceManager.GetString("Control_DocEditControl_ScriptUtilsASPFormUploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in new document:.
        /// </summary>
        public static string Control_DocEditView_CheckInNewDoc {
            get {
                return ResourceManager.GetString("Control_DocEditView_CheckInNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type:.
        /// </summary>
        public static string Control_DocEditView_DocType {
            get {
                return ResourceManager.GetString("Control_DocEditView_DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be empty!.
        /// </summary>
        public static string Control_DocEditView_EmptyValue {
            get {
                return ResourceManager.GetString("Control_DocEditView_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string Control_DocEditView_FileName {
            get {
                return ResourceManager.GetString("Control_DocEditView_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file NOT more than 50MB in file size; Check in process will fail
        ///            if uploading file takes more than 1 hour upon your internet connection!.
        /// </summary>
        public static string Control_DocEditView_LimitFileSize {
            get {
                return ResourceManager.GetString("Control_DocEditView_LimitFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string Control_DocEditView_SelectDate {
            get {
                return ResourceManager.GetString("Control_DocEditView_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change display fields is not allowed!.
        /// </summary>
        public static string Control_DocListControl_ChangeDisplayField {
            get {
                return ResourceManager.GetString("Control_DocListControl_ChangeDisplayField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change sort fields is not allowed!.
        /// </summary>
        public static string Control_DocListControl_ChangeSortField {
            get {
                return ResourceManager.GetString("Control_DocListControl_ChangeSortField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Document.
        /// </summary>
        public static string Control_DocListControl_NoDocument {
            get {
                return ResourceManager.GetString("Control_DocListControl_NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find list setting!.
        /// </summary>
        public static string Control_DocListControl_NoListSettingFound {
            get {
                return ResourceManager.GetString("Control_DocListControl_NoListSettingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result for search criteria: {0}.
        /// </summary>
        public static string Control_DocListControl_SearchResult {
            get {
                return ResourceManager.GetString("Control_DocListControl_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed system maximum number,first 500 documents returned, please apply/refine search criteria!.
        /// </summary>
        public static string Control_DocListControl_TooManyRecord {
            get {
                return ResourceManager.GetString("Control_DocListControl_TooManyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add action first.
        /// </summary>
        public static string Control_PermissionControl_AddAction {
            get {
                return ResourceManager.GetString("Control_PermissionControl_AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Control_PermissionControl_FullName {
            get {
                return ResourceManager.GetString("Control_PermissionControl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all member have permission for required actions, please assign permission to those member with * shown below!.
        /// </summary>
        public static string Control_PermissionControl_LackOfPermission {
            get {
                return ResourceManager.GetString("Control_PermissionControl_LackOfPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required action!.
        /// </summary>
        public static string Control_PermissionMemberControl_RequiredAction {
            get {
                return ResourceManager.GetString("Control_PermissionMemberControl_RequiredAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to all sub folders.
        /// </summary>
        public static string Control_PermissionMemberView_Apply {
            get {
                return ResourceManager.GetString("Control_PermissionMemberView_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission for {0}: {1}.
        /// </summary>
        public static string Control_PermissionMemberView_Permissions {
            get {
                return ResourceManager.GetString("Control_PermissionMemberView_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For Default View Action = Advanced Search).
        /// </summary>
        public static string Control_RequriedActionsControl_AdvancedSearchAction {
            get {
                return ResourceManager.GetString("Control_RequriedActionsControl_AdvancedSearchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Document Action:.
        /// </summary>
        public static string Control_RequriedActionsControl_DefaultDocAction {
            get {
                return ResourceManager.GetString("Control_RequriedActionsControl_DefaultDocAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default View Action:.
        /// </summary>
        public static string Control_RequriedActionsControl_DefaultViewAction {
            get {
                return ResourceManager.GetString("Control_RequriedActionsControl_DefaultViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result Display Action:.
        /// </summary>
        public static string Control_RequriedActionsControl_SearchResultDisplayAction {
            get {
                return ResourceManager.GetString("Control_RequriedActionsControl_SearchResultDisplayAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DoximDictionary_Active {
            get {
                return ResourceManager.GetString("DoximDictionary_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllUser.
        /// </summary>
        public static string DoximDictionary_AllUser {
            get {
                return ResourceManager.GetString("DoximDictionary_AllUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascend.
        /// </summary>
        public static string DoximDictionary_Ascend {
            get {
                return ResourceManager.GetString("DoximDictionary_Ascend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim Branding Information.
        /// </summary>
        public static string DoximDictionary_Branding {
            get {
                return ResourceManager.GetString("DoximDictionary_Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string DoximDictionary_Center {
            get {
                return ResourceManager.GetString("DoximDictionary_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim Company Name.
        /// </summary>
        public static string DoximDictionary_CompanyName {
            get {
                return ResourceManager.GetString("DoximDictionary_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string DoximDictionary_Completed {
            get {
                return ResourceManager.GetString("DoximDictionary_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descend.
        /// </summary>
        public static string DoximDictionary_Descend {
            get {
                return ResourceManager.GetString("DoximDictionary_Descend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim User First Name.
        /// </summary>
        public static string DoximDictionary_FirstName {
            get {
                return ResourceManager.GetString("DoximDictionary_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is.
        /// </summary>
        public static string DoximDictionary_Is {
            get {
                return ResourceManager.GetString("DoximDictionary_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim User Last Name.
        /// </summary>
        public static string DoximDictionary_LastName {
            get {
                return ResourceManager.GetString("DoximDictionary_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string DoximDictionary_Left {
            get {
                return ResourceManager.GetString("DoximDictionary_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string DoximDictionary_Locked {
            get {
                return ResourceManager.GetString("DoximDictionary_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUser.
        /// </summary>
        public static string DoximDictionary_NewUser {
            get {
                return ResourceManager.GetString("DoximDictionary_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DoximDictionary_None {
            get {
                return ResourceManager.GetString("DoximDictionary_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rule (No Requirement).
        /// </summary>
        public static string DoximDictionary_NoRule {
            get {
                return ResourceManager.GetString("DoximDictionary_NoRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string DoximDictionary_Not {
            get {
                return ResourceManager.GetString("DoximDictionary_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string DoximDictionary_Pending {
            get {
                return ResourceManager.GetString("DoximDictionary_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string DoximDictionary_Required {
            get {
                return ResourceManager.GetString("DoximDictionary_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string DoximDictionary_Right {
            get {
                return ResourceManager.GetString("DoximDictionary_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Rule (A minimum of 8 characters is required.).
        /// </summary>
        public static string DoximDictionary_StandardRule {
            get {
                return ResourceManager.GetString("DoximDictionary_StandardRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Rule (A minimum of 8 characters and a combination of both alpha and numeric characters are required.).
        /// </summary>
        public static string DoximDictionary_StrongRule {
            get {
                return ResourceManager.GetString("DoximDictionary_StrongRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string DoximDictionary_Suspend {
            get {
                return ResourceManager.GetString("DoximDictionary_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim User ID.
        /// </summary>
        public static string DoximDictionary_UserID {
            get {
                return ResourceManager.GetString("DoximDictionary_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim User Level.
        /// </summary>
        public static string DoximDictionary_UserLevel {
            get {
                return ResourceManager.GetString("DoximDictionary_UserLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to find procedure: {0}.
        /// </summary>
        public static string DoximEvent_NotFound {
            get {
                return ResourceManager.GetString("DoximEvent_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item index exceed item total!.
        /// </summary>
        public static string DoximGrid_IndexExceed {
            get {
                return ResourceManager.GetString("DoximGrid_IndexExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find grid: {0} !.
        /// </summary>
        public static string DoximGrid_NoGrid {
            get {
                return ResourceManager.GetString("DoximGrid_NoGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Display Fields.
        /// </summary>
        public static string DoximHead_ChangeFields {
            get {
                return ResourceManager.GetString("DoximHead_ChangeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click column name to sort alphabetically.
        /// </summary>
        public static string DoximHead_SortTitle {
            get {
                return ResourceManager.GetString("DoximHead_SortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find style folder, please contact system administrator!.
        /// </summary>
        public static string DoximLib_StyleFolderNotFound {
            get {
                return ResourceManager.GetString("DoximLib_StyleFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: Web path not exist..
        /// </summary>
        public static string DoximLib_WebPathNotFound {
            get {
                return ResourceManager.GetString("DoximLib_WebPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Row.
        /// </summary>
        public static string DoximNewItemBar_AddNewRow {
            get {
                return ResourceManager.GetString("DoximNewItemBar_AddNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Rows.
        /// </summary>
        public static string DoximNewItemBar_DeleteRow {
            get {
                return ResourceManager.GetString("DoximNewItemBar_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string DoximPage_First {
            get {
                return ResourceManager.GetString("DoximPage_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string DoximPage_FirstPage {
            get {
                return ResourceManager.GetString("DoximPage_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Page.
        /// </summary>
        public static string DoximPage_GotoPage {
            get {
                return ResourceManager.GetString("DoximPage_GotoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string DoximPage_Last {
            get {
                return ResourceManager.GetString("DoximPage_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string DoximPage_LastPage {
            get {
                return ResourceManager.GetString("DoximPage_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DoximPage_Next {
            get {
                return ResourceManager.GetString("DoximPage_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string DoximPage_NextPage {
            get {
                return ResourceManager.GetString("DoximPage_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string DoximPage_Previous {
            get {
                return ResourceManager.GetString("DoximPage_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string DoximPage_PreviousPage {
            get {
                return ResourceManager.GetString("DoximPage_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CMD!.
        /// </summary>
        public static string DoximProgress_Invalid {
            get {
                return ResourceManager.GetString("DoximProgress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving file into Doxim....
        /// </summary>
        public static string DoximProgress_MovingFile {
            get {
                return ResourceManager.GetString("DoximProgress_MovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading...{0}%.
        /// </summary>
        public static string DoximProgress_Uploading {
            get {
                return ResourceManager.GetString("DoximProgress_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string DoximProgress_Waiting {
            get {
                return ResourceManager.GetString("DoximProgress_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string DoximTab_Action {
            get {
                return ResourceManager.GetString("DoximTab_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Fields.
        /// </summary>
        public static string DoximTab_CommonFields {
            get {
                return ResourceManager.GetString("DoximTab_CommonFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string DoximTab_Criteria {
            get {
                return ResourceManager.GetString("DoximTab_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string DoximTab_Document {
            get {
                return ResourceManager.GetString("DoximTab_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string DoximTab_General {
            get {
                return ResourceManager.GetString("DoximTab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string DoximTab_Members {
            get {
                return ResourceManager.GetString("DoximTab_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTag.
        /// </summary>
        public static string DoximTab_MetaTag {
            get {
                return ResourceManager.GetString("DoximTab_MetaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string DoximTab_Navigation {
            get {
                return ResourceManager.GetString("DoximTab_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DoximTab_Password {
            get {
                return ResourceManager.GetString("DoximTab_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string DoximTab_Permission {
            get {
                return ResourceManager.GetString("DoximTab_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string DoximTab_Setting {
            get {
                return ResourceManager.GetString("DoximTab_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value List.
        /// </summary>
        public static string DoximTab_ValueList {
            get {
                return ResourceManager.GetString("DoximTab_ValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome String.
        /// </summary>
        public static string DoximTab_Welcome {
            get {
                return ResourceManager.GetString("DoximTab_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find document list Cache! {0}.
        /// </summary>
        public static string MasterPage_CacheNotFound {
            get {
                return ResourceManager.GetString("MasterPage_CacheNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Path! {0}.
        /// </summary>
        public static string MasterPage_InvalidPath {
            get {
                return ResourceManager.GetString("MasterPage_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission!.
        /// </summary>
        public static string MasterPage_InvalidPermission {
            get {
                return ResourceManager.GetString("MasterPage_InvalidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find item: [{0}] in document list cache!.
        /// </summary>
        public static string MasterPage_ItemNotFound {
            get {
                return ResourceManager.GetString("MasterPage_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find procedure: {0}.
        /// </summary>
        public static string MasterPage_PrecedureNotFound {
            get {
                return ResourceManager.GetString("MasterPage_PrecedureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for Action:.
        /// </summary>
        public static string MasterPageConfig_ActionConfiguration {
            get {
                return ResourceManager.GetString("MasterPageConfig_ActionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from document type actions.
        /// </summary>
        public static string MasterPageConfig_CopyDocAction {
            get {
                return ResourceManager.GetString("MasterPageConfig_CopyDocAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from actions of view: {0}.
        /// </summary>
        public static string MasterPageConfig_CopyViewAction {
            get {
                return ResourceManager.GetString("MasterPageConfig_CopyViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit.
        /// </summary>
        public static string MasterPageConfig_Inherit {
            get {
                return ResourceManager.GetString("MasterPageConfig_Inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not inheritable, please set its own configuration!.
        /// </summary>
        public static string MasterPageConfig_NotInheritable {
            get {
                return ResourceManager.GetString("MasterPageConfig_NotInheritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string MasterPageConfig_Override {
            get {
                return ResourceManager.GetString("MasterPageConfig_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set configuration.
        /// </summary>
        public static string MasterPageConfig_SetConfiguration {
            get {
                return ResourceManager.GetString("MasterPageConfig_SetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached end of list!.
        /// </summary>
        public static string MasterPageDocument_EndOfList {
            get {
                return ResourceManager.GetString("MasterPageDocument_EndOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string MasterPageMain_Waiting {
            get {
                return ResourceManager.GetString("MasterPageMain_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user is found!.
        /// </summary>
        public static string MemberSelectorView_NoUser {
            get {
                return ResourceManager.GetString("MemberSelectorView_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name and click search button.
        /// </summary>
        public static string MemberSelectorView_Search {
            get {
                return ResourceManager.GetString("MemberSelectorView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Ctrl or Shift key to select multiple names and click OK button..
        /// </summary>
        public static string MemberSelectorView_SelectMultiple {
            get {
                return ResourceManager.GetString("MemberSelectorView_SelectMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user and click OK button..
        /// </summary>
        public static string MemberSelectorView_SelectUser {
            get {
                return ResourceManager.GetString("MemberSelectorView_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many users is found, and only first 200 users can be displayed. Please refine search criteria..
        /// </summary>
        public static string MemberSelectorView_TooMany {
            get {
                return ResourceManager.GetString("MemberSelectorView_TooMany", resourceCulture);
            }
        }
    }
}
