//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MiscRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Web.MiscRes", typeof(MiscRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search.
        /// </summary>
        public static string Alt_Search {
            get {
                return ResourceManager.GetString("Alt_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- All Fields --.
        /// </summary>
        public static string ComboBox_AllFields {
            get {
                return ResourceManager.GetString("ComboBox_AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select....
        /// </summary>
        public static string ComboBox_PleaseSelect {
            get {
                return ResourceManager.GetString("ComboBox_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Path.
        /// </summary>
        public static string Label__EnablePath {
            get {
                return ResourceManager.GetString("Label__EnablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account#.
        /// </summary>
        public static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Label_Action {
            get {
                return ResourceManager.GetString("Label_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Label_Active {
            get {
                return ResourceManager.GetString("Label_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Label_Add {
            get {
                return ResourceManager.GetString("Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Actions.
        /// </summary>
        public static string Label_AddActions {
            get {
                return ResourceManager.GetString("Label_AddActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ALL.
        /// </summary>
        public static string Label_AddAll {
            get {
                return ResourceManager.GetString("Label_AddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter Message.
        /// </summary>
        public static string Label_AlterMessage {
            get {
                return ResourceManager.GetString("Label_AlterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Label_Approved {
            get {
                return ResourceManager.GetString("Label_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Label_Ascending {
            get {
                return ResourceManager.GetString("Label_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Current View.
        /// </summary>
        public static string Label_AssociateView {
            get {
                return ResourceManager.GetString("Label_AssociateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Label_Basic {
            get {
                return ResourceManager.GetString("Label_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string Label_ChangeEmail {
            get {
                return ResourceManager.GetString("Label_ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Label_ChangePassword {
            get {
                return ResourceManager.GetString("Label_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Label_Code {
            get {
                return ResourceManager.GetString("Label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Fields.
        /// </summary>
        public static string Label_CommonFields {
            get {
                return ResourceManager.GetString("Label_CommonFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Successfully.
        /// </summary>
        public static string Label_CompletedSuccessfully {
            get {
                return ResourceManager.GetString("Label_CompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Label_Condition {
            get {
                return ResourceManager.GetString("Label_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Label_Configuration {
            get {
                return ResourceManager.GetString("Label_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Label_Confirm {
            get {
                return ResourceManager.GetString("Label_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Label_Create {
            get {
                return ResourceManager.GetString("Label_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Common Field.
        /// </summary>
        public static string Label_CreateCommonField {
            get {
                return ResourceManager.GetString("Label_CreateCommonField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Company.
        /// </summary>
        public static string Label_CreateCompany {
            get {
                return ResourceManager.GetString("Label_CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MetaTag.
        /// </summary>
        public static string Label_CreateMetaTag {
            get {
                return ResourceManager.GetString("Label_CreateMetaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization.
        /// </summary>
        public static string Label_CreateOrganization {
            get {
                return ResourceManager.GetString("Label_CreateOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Print Job.
        /// </summary>
        public static string Label_CreatePrintJob {
            get {
                return ResourceManager.GetString("Label_CreatePrintJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sub.
        /// </summary>
        public static string Label_CreateSub {
            get {
                return ResourceManager.GetString("Label_CreateSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Label_Criteria {
            get {
                return ResourceManager.GetString("Label_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field List Values.
        /// </summary>
        public static string Label_CustomField {
            get {
                return ResourceManager.GetString("Label_CustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Page Size:.
        /// </summary>
        public static string Label_DefaultPageSize {
            get {
                return ResourceManager.GetString("Label_DefaultPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string Label_Del {
            get {
                return ResourceManager.GetString("Label_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del ALL.
        /// </summary>
        public static string Label_DelAll {
            get {
                return ResourceManager.GetString("Label_DelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Label_Descending {
            get {
                return ResourceManager.GetString("Label_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Label_Display {
            get {
                return ResourceManager.GetString("Label_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Label_Document {
            get {
                return ResourceManager.GetString("Label_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Missing.
        /// </summary>
        public static string Label_DocumentMissing {
            get {
                return ResourceManager.GetString("Label_DocumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string Label_DocumentType {
            get {
                return ResourceManager.GetString("Label_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click [here] or [Get Copy] button to download it..
        /// </summary>
        public static string Label_Download {
            get {
                return ResourceManager.GetString("Label_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click {0} or {1} button to download it..
        /// </summary>
        public static string Label_Download1 {
            get {
                return ResourceManager.GetString("Label_Download1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Label_Enable {
            get {
                return ResourceManager.GetString("Label_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Change Display Fields.
        /// </summary>
        public static string Label_EnableChangeDisplay {
            get {
                return ResourceManager.GetString("Label_EnableChangeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Change Page Size.
        /// </summary>
        public static string Label_EnableChangePageSize {
            get {
                return ResourceManager.GetString("Label_EnableChangePageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Change Sort Fields.
        /// </summary>
        public static string Label_EnableChangeSort {
            get {
                return ResourceManager.GetString("Label_EnableChangeSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Default Sorting.
        /// </summary>
        public static string Label_EnableDefaultSort {
            get {
                return ResourceManager.GetString("Label_EnableDefaultSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Header.
        /// </summary>
        public static string Label_EnableHeader {
            get {
                return ResourceManager.GetString("Label_EnableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tree.
        /// </summary>
        public static string Label_EnableTree {
            get {
                return ResourceManager.GetString("Label_EnableTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced.
        /// </summary>
        public static string Label_Enhanced {
            get {
                return ResourceManager.GetString("Label_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string Label_Equals {
            get {
                return ResourceManager.GetString("Label_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string Label_ErrorMessage {
            get {
                return ResourceManager.GetString("Label_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Label_Expired {
            get {
                return ResourceManager.GetString("Label_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Label_File {
            get {
                return ResourceManager.GetString("Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Label_Filename {
            get {
                return ResourceManager.GetString("Label_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string Label_FileName2 {
            get {
                return ResourceManager.GetString("Label_FileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string Label_First {
            get {
                return ResourceManager.GetString("Label_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlySheet.
        /// </summary>
        public static string Label_FlySheet {
            get {
                return ResourceManager.GetString("Label_FlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Label_Folder {
            get {
                return ResourceManager.GetString("Label_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For All Users.
        /// </summary>
        public static string Label_ForAllUsers {
            get {
                return ResourceManager.GetString("Label_ForAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormFill.
        /// </summary>
        public static string Label_FormFill {
            get {
                return ResourceManager.GetString("Label_FormFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For New Users.
        /// </summary>
        public static string Label_ForNewUsers {
            get {
                return ResourceManager.GetString("Label_ForNewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from file folder.
        /// </summary>
        public static string Label_FromFileFolder {
            get {
                return ResourceManager.GetString("Label_FromFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document from the queue.
        /// </summary>
        public static string Label_FromQueue {
            get {
                return ResourceManager.GetString("Label_FromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Label_FullName {
            get {
                return ResourceManager.GetString("Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Label_Generate {
            get {
                return ResourceManager.GetString("Label_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GetCopy].
        /// </summary>
        public static string Label_GetCopy {
            get {
                return ResourceManager.GetString("Label_GetCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Label_Group {
            get {
                return ResourceManager.GetString("Label_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Label_Header {
            get {
                return ResourceManager.GetString("Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Label_Height {
            get {
                return ResourceManager.GetString("Label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [here].
        /// </summary>
        public static string Label_Here {
            get {
                return ResourceManager.GetString("Label_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Label_Icon {
            get {
                return ResourceManager.GetString("Label_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impress#.
        /// </summary>
        public static string Label_Impress {
            get {
                return ResourceManager.GetString("Label_Impress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string Label_InActive {
            get {
                return ResourceManager.GetString("Label_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Label_Insert {
            get {
                return ResourceManager.GetString("Label_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Label_Invalid {
            get {
                return ResourceManager.GetString("Label_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tab!.
        /// </summary>
        public static string Label_InvalidTab {
            get {
                return ResourceManager.GetString("Label_InvalidTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Value List.
        /// </summary>
        public static string Label_IsValueList {
            get {
                return ResourceManager.GetString("Label_IsValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Value Multiple.
        /// </summary>
        public static string Label_IsValueMultiple {
            get {
                return ResourceManager.GetString("Label_IsValueMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Value Required.
        /// </summary>
        public static string Label_IsValueRequired {
            get {
                return ResourceManager.GetString("Label_IsValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Label_Last {
            get {
                return ResourceManager.GetString("Label_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastAction.
        /// </summary>
        public static string Label_LastAction {
            get {
                return ResourceManager.GetString("Label_LastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftChars.
        /// </summary>
        public static string Label_LeftChars {
            get {
                return ResourceManager.GetString("Label_LeftChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Label_Line {
            get {
                return ResourceManager.GetString("Label_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Label_List {
            get {
                return ResourceManager.GetString("Label_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings.
        /// </summary>
        public static string Label_ListSettingTitle {
            get {
                return ResourceManager.GetString("Label_ListSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Address.
        /// </summary>
        public static string Label_LocalAddress {
            get {
                return ResourceManager.GetString("Label_LocalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Label_Logout {
            get {
                return ResourceManager.GetString("Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterDetail.
        /// </summary>
        public static string Label_MasterDetail {
            get {
                return ResourceManager.GetString("Label_MasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Select.
        /// </summary>
        public static string Label_MemberSelect {
            get {
                return ResourceManager.GetString("Label_MemberSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Label_Message {
            get {
                return ResourceManager.GetString("Label_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTag.
        /// </summary>
        public static string Label_MetaTag {
            get {
                return ResourceManager.GetString("Label_MetaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string Label_NewGroup {
            get {
                return ResourceManager.GetString("Label_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Label_Next {
            get {
                return ResourceManager.GetString("Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document in print queue..
        /// </summary>
        public static string Label_NoDocument {
            get {
                return ResourceManager.GetString("Label_NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Label_None {
            get {
                return ResourceManager.GetString("Label_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Label_Number {
            get {
                return ResourceManager.GetString("Label_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Label_Of {
            get {
                return ResourceManager.GetString("Label_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on field:.
        /// </summary>
        public static string Label_OnField {
            get {
                return ResourceManager.GetString("Label_OnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Label_Open {
            get {
                return ResourceManager.GetString("Label_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in current window.
        /// </summary>
        public static string Label_OpenInCurrentWindow {
            get {
                return ResourceManager.GetString("Label_OpenInCurrentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        public static string Label_OpenInNewWindow {
            get {
                return ResourceManager.GetString("Label_OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Label_Order {
            get {
                return ResourceManager.GetString("Label_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Label_Organization {
            get {
                return ResourceManager.GetString("Label_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Label_Page {
            get {
                return ResourceManager.GetString("Label_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Label_Pending {
            get {
                return ResourceManager.GetString("Label_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel.
        /// </summary>
        public static string Label_Pixel {
            get {
                return ResourceManager.GetString("Label_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Label_Portfolio {
            get {
                return ResourceManager.GetString("Label_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortfolioFields.
        /// </summary>
        public static string Label_PortfolioFields {
            get {
                return ResourceManager.GetString("Label_PortfolioFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Label_Previous {
            get {
                return ResourceManager.GetString("Label_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Label_Print {
            get {
                return ResourceManager.GetString("Label_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        public static string Label_Processing {
            get {
                return ResourceManager.GetString("Label_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Label_Profile {
            get {
                return ResourceManager.GetString("Label_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Address.
        /// </summary>
        public static string Label_RemoteAddress {
            get {
                return ResourceManager.GetString("Label_RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Host.
        /// </summary>
        public static string Label_RemoteHost {
            get {
                return ResourceManager.GetString("Label_RemoteHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Label_Remove {
            get {
                return ResourceManager.GetString("Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Label_Report {
            get {
                return ResourceManager.GetString("Label_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string Label_Requested {
            get {
                return ResourceManager.GetString("Label_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Label_Required {
            get {
                return ResourceManager.GetString("Label_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Label_Send {
            get {
                return ResourceManager.GetString("Label_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent out.
        /// </summary>
        public static string Label_SentOut {
            get {
                return ResourceManager.GetString("Label_SentOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string Label_SortBy {
            get {
                return ResourceManager.GetString("Label_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort View By.
        /// </summary>
        public static string Label_SortViewBy {
            get {
                return ResourceManager.GetString("Label_SortViewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Label_Source {
            get {
                return ResourceManager.GetString("Label_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Label_Style {
            get {
                return ResourceManager.GetString("Label_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Label_Styles {
            get {
                return ResourceManager.GetString("Label_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        public static string Label_SubFolder {
            get {
                return ResourceManager.GetString("Label_SubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Label_Suspended {
            get {
                return ResourceManager.GetString("Label_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then By.
        /// </summary>
        public static string Label_Then_By {
            get {
                return ResourceManager.GetString("Label_Then_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string Label_Thumbnail {
            get {
                return ResourceManager.GetString("Label_Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string Label_TotalNo {
            get {
                return ResourceManager.GetString("Label_TotalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this action as it is referred by views!.
        /// </summary>
        public static string Label_UnableDeleteAction {
            get {
                return ResourceManager.GetString("Label_UnableDeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Label_URL {
            get {
                return ResourceManager.GetString("Label_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Label_Value {
            get {
                return ResourceManager.GetString("Label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Label_View {
            get {
                return ResourceManager.GetString("Label_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Criteria.
        /// </summary>
        public static string Label_ViewCriteria {
            get {
                return ResourceManager.GetString("Label_ViewCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string Label_Waiting {
            get {
                return ResourceManager.GetString("Label_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Label_Width {
            get {
                return ResourceManager.GetString("Label_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with view:.
        /// </summary>
        public static string Label_WithView {
            get {
                return ResourceManager.GetString("Label_WithView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Label_Workflow {
            get {
                return ResourceManager.GetString("Label_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML ID.
        /// </summary>
        public static string Label_XMLID {
            get {
                return ResourceManager.GetString("Label_XMLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please correct all invalid input in red. to see error description, move mouse over red input box..
        /// </summary>
        public static string View_ErrorMessage {
            get {
                return ResourceManager.GetString("View_ErrorMessage", resourceCulture);
            }
        }
    }
}
