//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Web.WebRes", typeof(WebRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBackIn document.
        /// </summary>
        public static string Doc_DocCheckBackIn {
            get {
                return ResourceManager.GetString("Doc_DocCheckBackIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to checkout document as it is checked out already!.
        /// </summary>
        public static string Doc_DocCheckOut_CheckoutAlready {
            get {
                return ResourceManager.GetString("Doc_DocCheckOut_CheckoutAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout action is canceled.
        /// </summary>
        public static string Doc_DocCheckOutControl_Cancel {
            get {
                return ResourceManager.GetString("Doc_DocCheckOutControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to checkout this document?.
        /// </summary>
        public static string Doc_DocCheckOutView_AreYouSure {
            get {
                return ResourceManager.GetString("Doc_DocCheckOutView_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Checkout.
        /// </summary>
        public static string Doc_DocCheckOutView_DocumentCheckout {
            get {
                return ResourceManager.GetString("Doc_DocCheckOutView_DocumentCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has been flagged as checked out successfully! but there is error during downloading file..
        /// </summary>
        public static string Doc_DocCheckOutView_Error {
            get {
                return ResourceManager.GetString("Doc_DocCheckOutView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Document successfully!.
        /// </summary>
        public static string Doc_DocCheckOutView_Succeed {
            get {
                return ResourceManager.GetString("Doc_DocCheckOutView_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action is canceled!.
        /// </summary>
        public static string Doc_DocDelete_Cancel {
            get {
                return ResourceManager.GetString("Doc_DocDelete_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this document?.
        /// </summary>
        public static string Doc_DocDeleteView_AreYouSure {
            get {
                return ResourceManager.GetString("Doc_DocDeleteView_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore file missing error?.
        /// </summary>
        public static string Doc_DocDeleteView_Ignore {
            get {
                return ResourceManager.GetString("Doc_DocDeleteView_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: File size over limit, Can&apos;t be attached. The file size must less then 2MB..
        /// </summary>
        public static string Doc_DocEmailControl_OverSize {
            get {
                return ResourceManager.GetString("Doc_DocEmailControl_OverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Doc_DocEmailView_Attach {
            get {
                return ResourceManager.GetString("Doc_DocEmailView_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address can&apos;t leave blank..
        /// </summary>
        public static string Doc_DocEmailView_EmailEmpty {
            get {
                return ResourceManager.GetString("Doc_DocEmailView_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender email address is empty, may cause sending error.
        /// </summary>
        public static string Doc_DocEmailView_EmailEmpty2 {
            get {
                return ResourceManager.GetString("Doc_DocEmailView_EmailEmpty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid E-mail Address! Please re-enter..
        /// </summary>
        public static string Doc_DocEmailView_InvalidEmail {
            get {
                return ResourceManager.GetString("Doc_DocEmailView_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail has been generated for information purposes only. Please do not reply..
        /// </summary>
        public static string Doc_DocEmailView_NoReply {
            get {
                return ResourceManager.GetString("Doc_DocEmailView_NoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Doc_DocEmailView_Subject {
            get {
                return ResourceManager.GetString("Doc_DocEmailView_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.  Flysheet requires PDF file type..
        /// </summary>
        public static string Doc_DocFlysheetControl_PDFRequire {
            get {
                return ResourceManager.GetString("Doc_DocFlysheetControl_PDFRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Doc_DocFlysheetView_Address {
            get {
                return ResourceManager.GetString("Doc_DocFlysheetView_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fly Sheet.
        /// </summary>
        public static string Doc_DocFlysheetView_FlySheet {
            get {
                return ResourceManager.GetString("Doc_DocFlysheetView_FlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite DateTime.
        /// </summary>
        public static string Doc_DocHistoryControl_OverwriteDateTime {
            get {
                return ResourceManager.GetString("Doc_DocHistoryControl_OverwriteDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Doc_DocHistoryControl_Title {
            get {
                return ResourceManager.GetString("Doc_DocHistoryControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Back In.
        /// </summary>
        public static string Doc_DocMenuActionsControl_CheckBackIn {
            get {
                return ResourceManager.GetString("Doc_DocMenuActionsControl_CheckBackIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Doc_DocMenuActionsControl_CheckOut {
            get {
                return ResourceManager.GetString("Doc_DocMenuActionsControl_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Check Out.
        /// </summary>
        public static string Doc_DocMenuActionsControl_UndoCheckOut {
            get {
                return ResourceManager.GetString("Doc_DocMenuActionsControl_UndoCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Doc_DocMenuBackToListControl_Backtolist {
            get {
                return ResourceManager.GetString("Doc_DocMenuBackToListControl_Backtolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By User.
        /// </summary>
        public static string Doc_DocNoteView_ByUser {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_ByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Note.
        /// </summary>
        public static string Doc_DocNoteView_CreateNewNote {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_CreateNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Note.
        /// </summary>
        public static string Doc_DocNoteView_DocumentNote {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_DocumentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        public static string Doc_DocNoteView_EditNote {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Maximum 2000 characters ---.
        /// </summary>
        public static string Doc_DocNoteView_Maximum {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notes for this document!.
        /// </summary>
        public static string Doc_DocNoteView_NoNotes {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Doc_DocNoteView_Note {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Created.
        /// </summary>
        public static string Doc_DocNoteView_TimeCreated {
            get {
                return ResourceManager.GetString("Doc_DocNoteView_TimeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open in a new window.
        /// </summary>
        public static string Doc_DocOpenPageControl_OpenNewWindow {
            get {
                return ResourceManager.GetString("Doc_DocOpenPageControl_OpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to print this image.
        /// </summary>
        public static string Doc_DocOpenPageControl_PrintImage {
            get {
                return ResourceManager.GetString("Doc_DocOpenPageControl_PrintImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found, Please contact your system Administrator!.
        /// </summary>
        public static string Doc_DocOpenTiff_FileNotFound {
            get {
                return ResourceManager.GetString("Doc_DocOpenTiff_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add this document to queue?.
        /// </summary>
        public static string Doc_DocPrintQueueAddView_AreYouSure {
            get {
                return ResourceManager.GetString("Doc_DocPrintQueueAddView_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The to queue operation canceled!.
        /// </summary>
        public static string Doc_DocPrintQueueAddView_Cancel {
            get {
                return ResourceManager.GetString("Doc_DocPrintQueueAddView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow is not configured yet, please contact administrator.
        /// </summary>
        public static string Doc_DocWorkFlowControl_Configure {
            get {
                return ResourceManager.GetString("Doc_DocWorkFlowControl_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action defined on this document!.
        /// </summary>
        public static string Doc_DocWorkFlowControl_NoAction {
            get {
                return ResourceManager.GetString("Doc_DocWorkFlowControl_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching document found!.
        /// </summary>
        public static string Doc_MasterDetailsView_NoDocument {
            get {
                return ResourceManager.GetString("Doc_MasterDetailsView_NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating failed. Please contact your administrator.
        /// </summary>
        public static string DssoAuthenticate_Authenticate {
            get {
                return ResourceManager.GetString("DssoAuthenticate_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom fields are not correctlly configured.
        /// </summary>
        public static string DssoAuthenticate_Custom {
            get {
                return ResourceManager.GetString("DssoAuthenticate_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your are not allowed login temporarily.
        /// </summary>
        public static string DssoAuthenticate_Login {
            get {
                return ResourceManager.GetString("DssoAuthenticate_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Remote access failed. Please contact your administrator.
        /// </summary>
        public static string DssoAuthenticate_Remote {
            get {
                return ResourceManager.GetString("DssoAuthenticate_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string Folder_FolderAdminControl_CreateFolder {
            get {
                return ResourceManager.GetString("Folder_FolderAdminControl_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sub folder.
        /// </summary>
        public static string Folder_FolderAdminControl_CreateNewSubFolder {
            get {
                return ResourceManager.GetString("Folder_FolderAdminControl_CreateNewSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Permission.
        /// </summary>
        public static string Folder_FolderAdminControl_FolderPermission {
            get {
                return ResourceManager.GetString("Folder_FolderAdminControl_FolderPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder profile.
        /// </summary>
        public static string Folder_FolderAdminControl_FolderProfile {
            get {
                return ResourceManager.GetString("Folder_FolderAdminControl_FolderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Folder_FolderAdminControl_Permission {
            get {
                return ResourceManager.GetString("Folder_FolderAdminControl_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Folder_FolderAdminControl_Profile {
            get {
                return ResourceManager.GetString("Folder_FolderAdminControl_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Permission.
        /// </summary>
        public static string Folder_FolderPermissionView_CreatePermission {
            get {
                return ResourceManager.GetString("Folder_FolderPermissionView_CreatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder profile is not allow to change, please contact system administrator!.
        /// </summary>
        public static string Folder_FolderProfileControl_ {
            get {
                return ResourceManager.GetString("Folder_FolderProfileControl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string Folder_FolderProfileControl_NewFolder {
            get {
                return ResourceManager.GetString("Folder_FolderProfileControl_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passed.
        /// </summary>
        public static string Folder_FolderProfileControl_Passed {
            get {
                return ResourceManager.GetString("Folder_FolderProfileControl_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Folder as well as the documents?.
        /// </summary>
        public static string Folder_FolderProfileView_DeleteAll {
            get {
                return ResourceManager.GetString("Folder_FolderProfileView_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Current Folder.
        /// </summary>
        public static string Folder_FolderProfileView_DeleteCurrentFolder {
            get {
                return ResourceManager.GetString("Folder_FolderProfileView_DeleteCurrentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Folder?.
        /// </summary>
        public static string Folder_FolderProfileView_DeleteFolder {
            get {
                return ResourceManager.GetString("Folder_FolderProfileView_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} document(s) under this folder..
        /// </summary>
        public static string Folder_FolderProfileView_DocumentCount {
            get {
                return ResourceManager.GetString("Folder_FolderProfileView_DocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore errors and force delete.
        /// </summary>
        public static string Folder_FolderProfileView_ForceDelete {
            get {
                return ResourceManager.GetString("Folder_FolderProfileView_ForceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subfolder.
        /// </summary>
        public static string Folder_FolderSubfolders_CreateSubfolder {
            get {
                return ResourceManager.GetString("Folder_FolderSubfolders_CreateSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Permission!.
        /// </summary>
        public static string Invalid_Permission {
            get {
                return ResourceManager.GetString("Invalid_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission on current page.
        /// </summary>
        public static string Invalid_PermissionOnCurrentPage {
            get {
                return ResourceManager.GetString("Invalid_PermissionOnCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L O G I N.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string LoginView_UserLogin {
            get {
                return ResourceManager.GetString("LoginView_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid portfolio default page setting, please contact system administrator!.
        /// </summary>
        public static string Navigate_Portfolio_InvalidSetting {
            get {
                return ResourceManager.GetString("Navigate_Portfolio_InvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid view default page setting, please contact system administrator!.
        /// </summary>
        public static string Navigate_View_InvalidSetting {
            get {
                return ResourceManager.GetString("Navigate_View_InvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Filter.
        /// </summary>
        public static string Portfolio_PortfolioViewsListControl_CommonFilter {
            get {
                return ResourceManager.GetString("Portfolio_PortfolioViewsListControl_CommonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel PJ Request.
        /// </summary>
        public static string PrintQueue_Job_PrintJobControl_CancelPJRequest {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobControl_CancelPJRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string PrintQueue_Job_PrintJobControl_DateTime {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobControl_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc#.
        /// </summary>
        public static string PrintQueue_Job_PrintJobControl_Doc {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobControl_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Jobs &lt;b&gt;Impression#: {0} &lt;b&gt;.
        /// </summary>
        public static string PrintQueue_Job_PrintJobControl_PrintJobs {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobControl_PrintJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Print Job.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_Back {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here To Get Your Print Job.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_Download {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_Merged {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_Merged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to merge files due to document missing..
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_MergedFailed {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_MergedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged Successfully!.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_MergedSuccessfully {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_MergedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Jobs: {0} Doc #: {1} Impression #: {2}.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_PrintJob {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_PrintJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped - Not a PDF File.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQControl_Skipped {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQControl_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Print File.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQView_GetPrintFile {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQView_GetPrintFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Jobs: {0}.
        /// </summary>
        public static string PrintQueue_Job_PrintJobQView_Total {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobQView_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_Cancelled {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel PJ Request.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_CancelPJRequest {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_CancelPJRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_Completed {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression#: {0}.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_Impression {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_Impression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In production.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_InProduction {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_InProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Jobs: {0}.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_Total {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untouched.
        /// </summary>
        public static string PrintQueue_Job_PrintJobView_Untouched {
            get {
                return ResourceManager.GetString("PrintQueue_Job_PrintJobView_Untouched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Queue Manager.
        /// </summary>
        public static string PrintQueue_Queue_PrintQueueAdminControl_PrintQueueManager {
            get {
                return ResourceManager.GetString("PrintQueue_Queue_PrintQueueAdminControl_PrintQueueManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string PrintQueue_Queue_PrintQueueAdminControl_Sender {
            get {
                return ResourceManager.GetString("PrintQueue_Queue_PrintQueueAdminControl_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim ECM.
        /// </summary>
        public static string User_DXMMain_DoximECM {
            get {
                return ResourceManager.GetString("User_DXMMain_DoximECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page uses frames, but your browser doesn&apos;t support them..
        /// </summary>
        public static string User_DXMMain_Frame {
            get {
                return ResourceManager.GetString("User_DXMMain_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string User_HeaderView_Administration {
            get {
                return ResourceManager.GetString("User_HeaderView_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string User_HeaderView_Feedback {
            get {
                return ResourceManager.GetString("User_HeaderView_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string User_HeaderView_Help {
            get {
                return ResourceManager.GetString("User_HeaderView_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string User_HeaderView_Hide {
            get {
                return ResourceManager.GetString("User_HeaderView_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Navigator.
        /// </summary>
        public static string User_HeaderView_HideNavigator {
            get {
                return ResourceManager.GetString("User_HeaderView_HideNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Doxim ECM.
        /// </summary>
        public static string User_HeaderView_LogoutDoximECM {
            get {
                return ResourceManager.GetString("User_HeaderView_LogoutDoximECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string User_HeaderView_MyProfile {
            get {
                return ResourceManager.GetString("User_HeaderView_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string User_HeaderView_Refresh {
            get {
                return ResourceManager.GetString("User_HeaderView_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string User_HeaderView_Show {
            get {
                return ResourceManager.GetString("User_HeaderView_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigator.
        /// </summary>
        public static string User_HeaderView_ShowNavigator {
            get {
                return ResourceManager.GetString("User_HeaderView_ShowNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Doxim, {0}.
        /// </summary>
        public static string User_HeaderView_WelcomeToDoxim {
            get {
                return ResourceManager.GetString("User_HeaderView_WelcomeToDoxim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Jobs.
        /// </summary>
        public static string User_HomeView_PrintJobs {
            get {
                return ResourceManager.GetString("User_HomeView_PrintJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Queue Manager.
        /// </summary>
        public static string User_HomeView_PrintQueueManager {
            get {
                return ResourceManager.GetString("User_HomeView_PrintQueueManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string User_MyProfileEmailView_NewEmail {
            get {
                return ResourceManager.GetString("User_MyProfileEmailView_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Email.
        /// </summary>
        public static string User_MyProfileEmailView_OldEmail {
            get {
                return ResourceManager.GetString("User_MyProfileEmailView_OldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string User_MyProfilePasswordView_ConfirmPassword {
            get {
                return ResourceManager.GetString("User_MyProfilePasswordView_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string User_MyProfilePasswordView_NewPassword {
            get {
                return ResourceManager.GetString("User_MyProfilePasswordView_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string User_MyProfilePasswordView_OldPassword {
            get {
                return ResourceManager.GetString("User_MyProfilePasswordView_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Rule.
        /// </summary>
        public static string User_MyProfilePasswordView_PasswordRule {
            get {
                return ResourceManager.GetString("User_MyProfilePasswordView_PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string User_MyProfileView_UserID {
            get {
                return ResourceManager.GetString("User_MyProfileView_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string User_MyProfileView_UserProfile {
            get {
                return ResourceManager.GetString("User_MyProfileView_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Queue.
        /// </summary>
        public static string User_PrintQueueControl_PrintQueue {
            get {
                return ResourceManager.GetString("User_PrintQueueControl_PrintQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string View_ViewDocsListView_And {
            get {
                return ResourceManager.GetString("View_ViewDocsListView_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        public static string View_ViewDocsListView_Applied {
            get {
                return ResourceManager.GetString("View_ViewDocsListView_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        public static string View_ViewDocsListView_Equal {
            get {
                return ResourceManager.GetString("View_ViewDocsListView_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string View_ViewDocsListView_Filter {
            get {
                return ResourceManager.GetString("View_ViewDocsListView_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string Web_LoginView_UserID {
            get {
                return ResourceManager.GetString("Web_LoginView_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Browsers now include:.
        /// </summary>
        public static string Website_BulletinBoard_Browsers {
            get {
                return ResourceManager.GetString("Website_BulletinBoard_Browsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Mac OS: Safari v5.0+.
        /// </summary>
        public static string Website_BulletinBoard_Mac {
            get {
                return ResourceManager.GetString("Website_BulletinBoard_Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Windows OS: IE v8+, Firefox v3.6+.
        /// </summary>
        public static string Website_BulletinBoard_Windows {
            get {
                return ResourceManager.GetString("Website_BulletinBoard_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doxim ECM.
        /// </summary>
        public static string WebSite_Main_DoximECM {
            get {
                return ResourceManager.GetString("WebSite_Main_DoximECM", resourceCulture);
            }
        }
    }
}
