//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessLogicRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessLogicRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Lib.BusinessLogicRes", typeof(BusinessLogicRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this action as it is referred by views!.
        /// </summary>
        public static string Action_Delete_UnableDeleteReferedView {
            get {
                return ResourceManager.GetString("Action_Delete_UnableDeleteReferedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the configuration node &apos;{0}Configuration&apos; not found in the xml string.
        /// </summary>
        public static string Action_ExtractConfig_ConfigurationNodeNotFound {
            get {
                return ResourceManager.GetString("Action_ExtractConfig_ConfigurationNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member action!.
        /// </summary>
        public static string Action_ValidateMemberActions_InvalidMemberAction {
            get {
                return ResourceManager.GetString("Action_ValidateMemberActions_InvalidMemberAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Batch_DeleteBatch_Deleting {
            get {
                return ResourceManager.GetString("Batch_DeleteBatch_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting folder: {0}/{1} document: {2}/{3}.
        /// </summary>
        public static string Batch_DeleteBatch_DeletingFolder {
            get {
                return ResourceManager.GetString("Batch_DeleteBatch_DeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient right to delete batch!.
        /// </summary>
        public static string Batch_DeleteBatch_NoRightDeleteBatch {
            get {
                return ResourceManager.GetString("Batch_DeleteBatch_NoRightDeleteBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid catalog, can not be empty!.
        /// </summary>
        public static string Batch_List_InvalidCatalog {
            get {
                return ResourceManager.GetString("Batch_List_InvalidCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported catalog!.
        /// </summary>
        public static string Batch_List_UnsupportedCatalog {
            get {
                return ResourceManager.GetString("Batch_List_UnsupportedCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateGroupBy only accepts D, M and Y..
        /// </summary>
        public static string CheckInHistory_DateGroupBy_OnlyAccepts {
            get {
                return ResourceManager.GetString("CheckInHistory_DateGroupBy_OnlyAccepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria can not be null..
        /// </summary>
        public static string CheckInHistory_GetSumImpl_CriteriaNoNull {
            get {
                return ResourceManager.GetString("CheckInHistory_GetSumImpl_CriteriaNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only monthly summary has been implemented!.
        /// </summary>
        public static string CheckInHistory_GetSumImpl_OnlyMonthlySummary {
            get {
                return ResourceManager.GetString("CheckInHistory_GetSumImpl_OnlyMonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectID can not be null or empty!.
        /// </summary>
        public static string CheckInHistory_ObjectID_CantBeNull {
            get {
                return ResourceManager.GetString("CheckInHistory_ObjectID_CantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectID must start with O, C or D..
        /// </summary>
        public static string CheckInHistory_ObjectID_MustStartWith {
            get {
                return ResourceManager.GetString("CheckInHistory_ObjectID_MustStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been tampered..
        /// </summary>
        public static string CheckInHistory_Validate_DataTempered {
            get {
                return ResourceManager.GetString("CheckInHistory_Validate_DataTempered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: input an invalid date value to a date field..
        /// </summary>
        public static string Criteria_buildDateField_InvalidDateValue {
            get {
                return ResourceManager.GetString("Criteria_buildDateField_InvalidDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid User Info must be provided in Criteria..
        /// </summary>
        public static string Criteria_BuildField_MustProvideValidUserInfo {
            get {
                return ResourceManager.GetString("Criteria_BuildField_MustProvideValidUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found custom field values in Criteria, check if user custom fields are empty..
        /// </summary>
        public static string Criteria_BuildField_NotFoundCustomFieldValues {
            get {
                return ResourceManager.GetString("Criteria_BuildField_NotFoundCustomFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1} on {2:yyyy-MM-dd HH:mm:ss} (GMT).
        /// </summary>
        public static string Document_CheckinNoLic_ByUser {
            get {
                return ResourceManager.GetString("Document_CheckinNoLic_ByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked back in.
        /// </summary>
        public static string Document_CheckInStream_CheckedBackIn {
            get {
                return ResourceManager.GetString("Document_CheckInStream_CheckedBackIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked in.
        /// </summary>
        public static string Document_CheckInStream_CheckedIn {
            get {
                return ResourceManager.GetString("Document_CheckInStream_CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked out.
        /// </summary>
        public static string Document_CheckInStream_CheckedOut {
            get {
                return ResourceManager.GetString("Document_CheckInStream_CheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Document_CheckInStream_Modified {
            get {
                return ResourceManager.GetString("Document_CheckInStream_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo check out.
        /// </summary>
        public static string Document_CheckInStream_UndoCheckOut {
            get {
                return ResourceManager.GetString("Document_CheckInStream_UndoCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From can not be null or empty..
        /// </summary>
        public static string Document_Email_FromNoNull {
            get {
                return ResourceManager.GetString("Document_Email_FromNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To can not be null or empty..
        /// </summary>
        public static string Document_Email_ToNoNull {
            get {
                return ResourceManager.GetString("Document_Email_ToNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find Email action on view {0}-{1}.
        /// </summary>
        public static string Document_EmailDefault_FailedFindEmail {
            get {
                return ResourceManager.GetString("Document_EmailDefault_FailedFindEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action {0} is not a valid Email Action. .
        /// </summary>
        public static string Document_GetFromInEmailActionConfig_NotValidEmailAction {
            get {
                return ResourceManager.GetString("Document_GetFromInEmailActionConfig_NotValidEmailAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:{0} doesn&apos;t implement BizClassAttribute.
        /// </summary>
        public static string EventLog_AddBizObjectInfo_NotImplementBizClassAttribute {
            get {
                return ResourceManager.GetString("EventLog_AddBizObjectInfo_NotImplementBizClassAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:{0} doesn&apos;t implement BizClassKeyAttribute.
        /// </summary>
        public static string EventLog_AddBizObjectInfo_NotImplementBizClassKey {
            get {
                return ResourceManager.GetString("EventLog_AddBizObjectInfo_NotImplementBizClassKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not support nested collection type for--{0}.
        /// </summary>
        public static string EventLog_AddCollectionInfo_NotSupportNestedCollectionType {
            get {
                return ResourceManager.GetString("EventLog_AddCollectionInfo_NotSupportNestedCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeSetCollection can not be null!.
        /// </summary>
        public static string EventLog_SetChangeSetCollection_changeSetCollectionNotNull {
            get {
                return ResourceManager.GetString("EventLog_SetChangeSetCollection_changeSetCollectionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete has been called!.
        /// </summary>
        public static string EventLogScope_Complete_CompleteCalled {
            get {
                return ResourceManager.GetString("EventLogScope_Complete_CompleteCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLogScope.
        /// </summary>
        public static string EventLogScope_Complete_EventLogScope {
            get {
                return ResourceManager.GetString("EventLogScope_Complete_EventLogScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid thread!.
        /// </summary>
        public static string EventLogScope_Dispose_InvalidThread {
            get {
                return ResourceManager.GetString("EventLogScope_Dispose_InvalidThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find field: {0}!.
        /// </summary>
        public static string Field_ConvertFieldCollection_UnableFindField {
            get {
                return ResourceManager.GetString("Field_ConvertFieldCollection_UnableFindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient right to delete the folder..
        /// </summary>
        public static string Folder_CheckDeletePermission_NoRightDeleteFolder {
            get {
                return ResourceManager.GetString("Folder_CheckDeletePermission_NoRightDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting document: {0}/{1}.
        /// </summary>
        public static string Folder_DeleteSharedFolder_DeletingDocument {
            get {
                return ResourceManager.GetString("Folder_DeleteSharedFolder_DeletingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete MetaTags with referenced Documents..
        /// </summary>
        public static string MetaTag_Delete_CantDeleteWithReferencedDoc {
            get {
                return ResourceManager.GetString("MetaTag_Delete_CantDeleteWithReferencedDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  datatype,  Please check metatag value list data format..
        /// </summary>
        public static string MetaTag_Update_PleaseCheckListDataFormat {
            get {
                return ResourceManager.GetString("MetaTag_Update_PleaseCheckListDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  list value, Please check all document&apos;s metatag value data format..
        /// </summary>
        public static string MetaTag_Update_PleaseCheckValueDataFormat {
            get {
                return ResourceManager.GetString("MetaTag_Update_PleaseCheckValueDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  list value to boolean, Please delete all of list value..
        /// </summary>
        public static string MetaTag_Update_PleaseDeleteListValue {
            get {
                return ResourceManager.GetString("MetaTag_Update_PleaseDeleteListValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is referenced by documents, can&apos;t be deleted.
        /// </summary>
        public static string MetaTagList_Delete_ReferencedByDocuments {
            get {
                return ResourceManager.GetString("MetaTagList_Delete_ReferencedByDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is referenced by documents, can&apos;t be changed.
        /// </summary>
        public static string MetaTagList_Update_ReferencedByDocuments {
            get {
                return ResourceManager.GetString("MetaTagList_Update_ReferencedByDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding Rule is not correct.
        /// </summary>
        public static string PortfolioFieldMapping_ApplyRule_PaddingRuleNotCorrect {
            get {
                return ResourceManager.GetString("PortfolioFieldMapping_ApplyRule_PaddingRuleNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask rule is not correct.
        /// </summary>
        public static string PortfolioFieldMapping_MaskRule_PaddingRuleNotCorrect {
            get {
                return ResourceManager.GetString("PortfolioFieldMapping_MaskRule_PaddingRuleNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform Rule defination is not correct!.
        /// </summary>
        public static string PortfolioFieldMapping_MaskRule_TransformRuleNotCorrect {
            get {
                return ResourceManager.GetString("PortfolioFieldMapping_MaskRule_TransformRuleNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to calculate page number of {0}.
        /// </summary>
        public static string PrintQueue_GetPDFPageCount_FailedCalculatePageNumber {
            get {
                return ResourceManager.GetString("PrintQueue_GetPDFPageCount_FailedCalculatePageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ItemID: {0}!.
        /// </summary>
        public static string SearchEngine_ItemID_InvalidItemID {
            get {
                return ResourceManager.GetString("SearchEngine_ItemID_InvalidItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission!.
        /// </summary>
        public static string User_ChangePassword_InvalidPermission {
            get {
                return ResourceManager.GetString("User_ChangePassword_InvalidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original password incorrect..
        /// </summary>
        public static string User_ChangePassword_OriginalPasswordIncorrect {
            get {
                return ResourceManager.GetString("User_ChangePassword_OriginalPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid catalog, can not be empty!.
        /// </summary>
        public static string User_List_InvalidCatalog {
            get {
                return ResourceManager.GetString("User_List_InvalidCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, Invalid Company ID: {0}, please contact system administrator!.
        /// </summary>
        public static string User_Login_InvalidCompanyIDContactAdmin {
            get {
                return ResourceManager.GetString("User_Login_InvalidCompanyIDContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, Invalid User ID or Password!.
        /// </summary>
        public static string User_Login_InvalidUserIDPWD {
            get {
                return ResourceManager.GetString("User_Login_InvalidUserIDPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, Invalid User ID or Password, After {0} more time(s) retry, your account will be locked!.
        /// </summary>
        public static string User_Login_InvalidUserIDPWD_Retry {
            get {
                return ResourceManager.GetString("User_Login_InvalidUserIDPWD_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, User Approval Still Pending!.
        /// </summary>
        public static string User_Login_UserApprovalPending {
            get {
                return ResourceManager.GetString("User_Login_UserApprovalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, User Locked!.
        /// </summary>
        public static string User_Login_UserLocked {
            get {
                return ResourceManager.GetString("User_Login_UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, User locked, please contact system administrator!.
        /// </summary>
        public static string User_Login_UserLockedContactAdmin {
            get {
                return ResourceManager.GetString("User_Login_UserLockedContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, User locked, please wait {0} minute(s) to retry!.
        /// </summary>
        public static string User_Login_UserLockedRetry {
            get {
                return ResourceManager.GetString("User_Login_UserLockedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, User Suspended!.
        /// </summary>
        public static string User_Login_UserSuspended {
            get {
                return ResourceManager.GetString("User_Login_UserSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password!.
        /// </summary>
        public static string User_Validate_InvalidPassword {
            get {
                return ResourceManager.GetString("User_Validate_InvalidPassword", resourceCulture);
            }
        }
    }
}
