//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Lib.CommonRes", typeof(CommonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic stamp url path can not be empty!.
        /// </summary>
        public static string ActionCfg_StampConfiguration_StampFileToStream_EmptyStampURL {
            get {
                return ResourceManager.GetString("ActionCfg_StampConfiguration_StampFileToStream_EmptyStampURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal URI format is incorrect, please reconfig it in company setting!.
        /// </summary>
        public static string Composite_AccessPath_Url {
            get {
                return ResourceManager.GetString("Composite_AccessPath_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please config template file first..
        /// </summary>
        public static string Composite_FormFill2Stream_Config {
            get {
                return ResourceManager.GetString("Composite_FormFill2Stream_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find template file: {0}.
        /// </summary>
        public static string Composite_FormFill2Stream_Template {
            get {
                return ResourceManager.GetString("Composite_FormFill2Stream_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlySheet: {0} not found, Please contact your system Administrator..
        /// </summary>
        public static string Composite_MergeFlySheet_FlySheet {
            get {
                return ResourceManager.GetString("Composite_MergeFlySheet_FlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old code has been obsoleted:dbconnectionstring=System.Configuration.ConfigurationSettings.AppSettings[\&quot;DOXIM DB CONNECTION\&quot;].
        /// </summary>
        public static string Configuration_DBConnectionString_Error {
            get {
                return ResourceManager.GetString("Configuration_DBConnectionString_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t wrap null stream.
        /// </summary>
        public static string DocStream_DocStream_Null {
            get {
                return ResourceManager.GetString("DocStream_DocStream_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must declare key property.
        /// </summary>
        public static string EventLogUtility_CompareCollection_Key {
            get {
                return ResourceManager.GetString("EventLogUtility_CompareCollection_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison object must be of the same type..
        /// </summary>
        public static string EventLogUtility_PropertiesEqual_Comparison {
            get {
                return ResourceManager.GetString("EventLogUtility_PropertiesEqual_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not support --- {0}.
        /// </summary>
        public static string Helper_BindToType_NotSupport {
            get {
                return ResourceManager.GetString("Helper_BindToType_NotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to write message into log file.
        /// </summary>
        public static string Logger_Log_Fail {
            get {
                return ResourceManager.GetString("Logger_Log_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open log file!.
        /// </summary>
        public static string Logger_Open_Fail {
            get {
                return ResourceManager.GetString("Logger_Open_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BatchesDocumentType Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_BatchesDocumentTypeID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_BatchesDocumentTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Batch Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_BatchID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_BatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyBatches Id, unable to convert to integer.
        /// </summary>
        public static string PageItem_GetInfo_CompanyBatchesID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyBatchesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyCustomFields Id, unable to convert to integer.
        /// </summary>
        public static string PageItem_GetInfo_CompanyCustomFieldsID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyCustomFieldsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyDocumentTypes Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_CompanyDocumentTypesID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyDocumentTypesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyFolders Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_CompanyFoldersID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyFoldersID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyGroups Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_CompanyGroupsID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyGroupsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Company Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_CompanyID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyPortfolios Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_CompanyPortfoliosID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CompanyPortfoliosID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CustomField Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_CustomFieldID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_CustomFieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DocumentType Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_DocumentTypeID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_DocumentTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FolderAdmin Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_FolderAdminID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_FolderAdminID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Folder Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_FolderID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_FolderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Group Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_GroupID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_GroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MetaTag Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_MetaTagID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_MetaTagID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Organization Id, unable to convert to integer.
        /// </summary>
        public static string PageItem_GetInfo_OrganizationID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_OrganizationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PortfolioAdmin Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_PortfolioAdminID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_PortfolioAdminID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Portfolio Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_PortfolioID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_PortfolioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_UserID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ViewAdmin Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_ViewAdminID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_ViewAdminID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid View Id, unable to convert to integer!.
        /// </summary>
        public static string PageItem_GetInfo_ViewID {
            get {
                return ResourceManager.GetString("PageItem_GetInfo_ViewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type {0}.
        /// </summary>
        public static string PageItem_GetPageItem_Type {
            get {
                return ResourceManager.GetString("PageItem_GetPageItem_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string PageItem_GetPageItem_User {
            get {
                return ResourceManager.GetString("PageItem_GetPageItem_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid itemType or action! {0}.
        /// </summary>
        public static string PageItem_GetUrl_Invalid {
            get {
                return ResourceManager.GetString("PageItem_GetUrl_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressID is more than Maximum defination.
        /// </summary>
        public static string Progress_ID {
            get {
                return ResourceManager.GetString("Progress_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ProgressIDs have been occupied.
        /// </summary>
        public static string Progress_Occupied {
            get {
                return ResourceManager.GetString("Progress_Occupied", resourceCulture);
            }
        }
    }
}
