//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAccessRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAccessRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Lib.DataAccessRes", typeof(DataAccessRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyId and DoctypeId cannot be zero..
        /// </summary>
        public static string BatchData_List_CamanyIdCantBe0 {
            get {
                return ResourceManager.GetString("BatchData_List_CamanyIdCantBe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CheckInHistory ID!.
        /// </summary>
        public static string CheckInHistoryData_GetInfo_InvalidCheckInHistoryID {
            get {
                return ResourceManager.GetString("CheckInHistoryData_GetInfo_InvalidCheckInHistoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code!.
        /// </summary>
        public static string ConditionDefData_GetInfo_InvalidCode {
            get {
                return ResourceManager.GetString("ConditionDefData_GetInfo_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CFid!!!.
        /// </summary>
        public static string CustomFieldListData_DeleteByCFid_InvalidCFid {
            get {
                return ResourceManager.GetString("CustomFieldListData_DeleteByCFid_InvalidCFid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid info ID!.
        /// </summary>
        public static string CustomFieldListData_Update_InvalidInfoID {
            get {
                return ResourceManager.GetString("CustomFieldListData_Update_InvalidInfoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty search criteria!.
        /// </summary>
        public static string CustomFieldValueData_SearchByMultipleField_EmptySearchCriteria {
            get {
                return ResourceManager.GetString("CustomFieldValueData_SearchByMultipleField_EmptySearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document info!.
        /// </summary>
        public static string DocumentData_Insert_InvalidDocumentInfo {
            get {
                return ResourceManager.GetString("DocumentData_Insert_InvalidDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid docID!.
        /// </summary>
        public static string DocumentData_UpdateStatus_InvalidDocID {
            get {
                return ResourceManager.GetString("DocumentData_UpdateStatus_InvalidDocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid docID or version!.
        /// </summary>
        public static string DocumentHistoryData_GetInfo_InvalidDocIDVersion {
            get {
                return ResourceManager.GetString("DocumentHistoryData_GetInfo_InvalidDocIDVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagID:{0} is invalid!.
        /// </summary>
        public static string FieldData_GetFieldID_TagIDInvalid {
            get {
                return ResourceManager.GetString("FieldData_GetFieldID_TagIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldID:{0} is invalid!.
        /// </summary>
        public static string FieldData_GetTagID_FieldIDInvalid {
            get {
                return ResourceManager.GetString("FieldData_GetTagID_FieldIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Updating Folder Path, Invalid Folder ID!.
        /// </summary>
        public static string FolderData_UpdatePath_ErrorUpdatingFolderPath {
            get {
                return ResourceManager.GetString("FolderData_UpdatePath_ErrorUpdatingFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not support data type--.
        /// </summary>
        public static string MetaTagData_IsMetaTagAllValuesOfDataType_NotSupportDataType {
            get {
                return ResourceManager.GetString("MetaTagData_IsMetaTagAllValuesOfDataType_NotSupportDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tagValueInfo!.
        /// </summary>
        public static string MetaTagValueData_Update_InvalidTagValueInfo {
            get {
                return ResourceManager.GetString("MetaTagValueData_Update_InvalidTagValueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid note!.
        /// </summary>
        public static string NoteData_Delete_InvalidNote {
            get {
                return ResourceManager.GetString("NoteData_Delete_InvalidNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid note ID!.
        /// </summary>
        public static string NoteData_Update_InvalidNoteID {
            get {
                return ResourceManager.GetString("NoteData_Update_InvalidNoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Field.
        /// </summary>
        public static string PortfolioFieldData_GetInfo_CommonField {
            get {
                return ResourceManager.GetString("PortfolioFieldData_GetInfo_CommonField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on inserting record!.
        /// </summary>
        public static string PortfolioFieldMappingData_ErrorOnInserting {
            get {
                return ResourceManager.GetString("PortfolioFieldMappingData_ErrorOnInserting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: input an invalid date value to a date field..
        /// </summary>
        public static string SearchEngineData_BuildDateField {
            get {
                return ResourceManager.GetString("SearchEngineData_BuildDateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid User Info must be provided in Criteria..
        /// </summary>
        public static string SearchEngineData_BuildField_MustProvideUserInfo {
            get {
                return ResourceManager.GetString("SearchEngineData_BuildField_MustProvideUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User does not have valid Custom Field value.  Contact an Administrator..
        /// </summary>
        public static string SearchEngineData_BuildField_UserHasNoValidCustomField {
            get {
                return ResourceManager.GetString("SearchEngineData_BuildField_UserHasNoValidCustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid objectType: {0}!.
        /// </summary>
        public static string SearchEngineData_BuildJoinClause_InvalidObjectType {
            get {
                return ResourceManager.GetString("SearchEngineData_BuildJoinClause_InvalidObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid join operator!.
        /// </summary>
        public static string SearchEngineData_BuildWhereClause_InvalidJoinOperator {
            get {
                return ResourceManager.GetString("SearchEngineData_BuildWhereClause_InvalidJoinOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many items found, please contact system administrator!.
        /// </summary>
        public static string SearchEngineData_SpCatalog_TooManyItemsFound {
            get {
                return ResourceManager.GetString("SearchEngineData_SpCatalog_TooManyItemsFound", resourceCulture);
            }
        }
    }
}
