//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Lib.DefsRes", typeof(DefsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read document.
        /// </summary>
        public static string ACD_Descr_1 {
            get {
                return ResourceManager.GetString("ACD_Descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Views In Portfolio.
        /// </summary>
        public static string ACD_Descr_12 {
            get {
                return ResourceManager.GetString("ACD_Descr_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify document.
        /// </summary>
        public static string ACD_Descr_2 {
            get {
                return ResourceManager.GetString("ACD_Descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string ACD_Descr_3 {
            get {
                return ResourceManager.GetString("ACD_Descr_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chech in / out document.
        /// </summary>
        public static string ACD_Descr_4 {
            get {
                return ResourceManager.GetString("ACD_Descr_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Docs In View.
        /// </summary>
        public static string ACD_Descr_5 {
            get {
                return ResourceManager.GetString("ACD_Descr_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Docs In Folder.
        /// </summary>
        public static string ACD_Descr_8 {
            get {
                return ResourceManager.GetString("ACD_Descr_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string ACD_Name_1 {
            get {
                return ResourceManager.GetString("ACD_Name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Search.
        /// </summary>
        public static string ACD_Name_10 {
            get {
                return ResourceManager.GetString("ACD_Name_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Search.
        /// </summary>
        public static string ACD_Name_11 {
            get {
                return ResourceManager.GetString("ACD_Name_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List .
        /// </summary>
        public static string ACD_Name_12 {
            get {
                return ResourceManager.GetString("ACD_Name_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string ACD_Name_2 {
            get {
                return ResourceManager.GetString("ACD_Name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ACD_Name_3 {
            get {
                return ResourceManager.GetString("ACD_Name_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Control.
        /// </summary>
        public static string ACD_Name_4 {
            get {
                return ResourceManager.GetString("ACD_Name_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ACD_Name_5 {
            get {
                return ResourceManager.GetString("ACD_Name_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Search.
        /// </summary>
        public static string ACD_Name_6 {
            get {
                return ResourceManager.GetString("ACD_Name_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ACD_Name_7 {
            get {
                return ResourceManager.GetString("ACD_Name_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ACD_Name_8 {
            get {
                return ResourceManager.GetString("ACD_Name_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flysheet.
        /// </summary>
        public static string AD_Descr_00716D2963C04736BE51D9CACF7A39D8 {
            get {
                return ResourceManager.GetString("AD_Descr_00716D2963C04736BE51D9CACF7A39D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email With Insert.
        /// </summary>
        public static string AD_Descr_0D678C406DB34580B7F17F3A42D2F60C {
            get {
                return ResourceManager.GetString("AD_Descr_0D678C406DB34580B7F17F3A42D2F60C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With FormFill.
        /// </summary>
        public static string AD_Descr_0ECB14DC0F01498EA41B136BEC154A7F {
            get {
                return ResourceManager.GetString("AD_Descr_0ECB14DC0F01498EA41B136BEC154A7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy With  FormFill.
        /// </summary>
        public static string AD_Descr_29145036F2A5497897DAC87672EC5194 {
            get {
                return ResourceManager.GetString("AD_Descr_29145036F2A5497897DAC87672EC5194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email With Stamp.
        /// </summary>
        public static string AD_Descr_326BE88BDB514C4F9A023AB1423F2355 {
            get {
                return ResourceManager.GetString("AD_Descr_326BE88BDB514C4F9A023AB1423F2355", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Document.
        /// </summary>
        public static string AD_Descr_36C0CA04B70F45398FC8AC44714BD622 {
            get {
                return ResourceManager.GetString("AD_Descr_36C0CA04B70F45398FC8AC44714BD622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy With Insert.
        /// </summary>
        public static string AD_Descr_38A0551356914C92A02D64921AACBB24 {
            get {
                return ResourceManager.GetString("AD_Descr_38A0551356914C92A02D64921AACBB24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Insert.
        /// </summary>
        public static string AD_Descr_395AC95CCE7D422FBE1A0F29CCA500B1 {
            get {
                return ResourceManager.GetString("AD_Descr_395AC95CCE7D422FBE1A0F29CCA500B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Stamp.
        /// </summary>
        public static string AD_Descr_3FE333F79178490C83CB66F154480F13 {
            get {
                return ResourceManager.GetString("AD_Descr_3FE333F79178490C83CB66F154480F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In New Document In  Folder.
        /// </summary>
        public static string AD_Descr_4AFC11E6E9924A0F9BDFC0CC42FF9A0B {
            get {
                return ResourceManager.GetString("AD_Descr_4AFC11E6E9924A0F9BDFC0CC42FF9A0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History.
        /// </summary>
        public static string AD_Descr_4D1643AE425748EA81B2C2D36F133C1B {
            get {
                return ResourceManager.GetString("AD_Descr_4D1643AE425748EA81B2C2D36F133C1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string AD_Descr_59FF20A3A7C345A1A267BAD4A3B5219A {
            get {
                return ResourceManager.GetString("AD_Descr_59FF20A3A7C345A1A267BAD4A3B5219A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Permission.
        /// </summary>
        public static string AD_Descr_673B87A134BF4CE8879F755CB1B2DF02 {
            get {
                return ResourceManager.GetString("AD_Descr_673B87A134BF4CE8879F755CB1B2DF02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        public static string AD_Descr_6862EA743C6B44F499D1B3DDB4725152 {
            get {
                return ResourceManager.GetString("AD_Descr_6862EA743C6B44F499D1B3DDB4725152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Document.
        /// </summary>
        public static string AD_Descr_6BA3674F0FD9485986EFAA9BA082A830 {
            get {
                return ResourceManager.GetString("AD_Descr_6BA3674F0FD9485986EFAA9BA082A830", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Detail Info.
        /// </summary>
        public static string AD_Descr_72F6509C447940D2B708BEAF06F153F8 {
            get {
                return ResourceManager.GetString("AD_Descr_72F6509C447940D2B708BEAF06F153F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View Documents.
        /// </summary>
        public static string AD_Descr_78FB13B449D5455BAE408CB8BA6B23E7 {
            get {
                return ResourceManager.GetString("AD_Descr_78FB13B449D5455BAE408CB8BA6B23E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Documents In Folder.
        /// </summary>
        public static string AD_Descr_803D22369ADB4037A315B542567A9DB3 {
            get {
                return ResourceManager.GetString("AD_Descr_803D22369ADB4037A315B542567A9DB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List With Tiff Thumbnail.
        /// </summary>
        public static string AD_Descr_804492E7DBC947EEB3B1C750CC9B427E {
            get {
                return ResourceManager.GetString("AD_Descr_804492E7DBC947EEB3B1C750CC9B427E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out / Check Back In.
        /// </summary>
        public static string AD_Descr_97156B7BF78B4F5CAD11D2217732D947 {
            get {
                return ResourceManager.GetString("AD_Descr_97156B7BF78B4F5CAD11D2217732D947", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal-detail.
        /// </summary>
        public static string AD_Descr_99B76763F2FB45BFAE43854DDED47EF6 {
            get {
                return ResourceManager.GetString("AD_Descr_99B76763F2FB45BFAE43854DDED47EF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master-Detail.
        /// </summary>
        public static string AD_Descr_AD2B9A7F2AA947C8B744F5CA3CC2032B {
            get {
                return ResourceManager.GetString("AD_Descr_AD2B9A7F2AA947C8B744F5CA3CC2032B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AD_Descr_B4439FA900564283BAA55CE250312247 {
            get {
                return ResourceManager.GetString("AD_Descr_B4439FA900564283BAA55CE250312247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email With FormFill.
        /// </summary>
        public static string AD_Descr_C58336F81569406F91A27916B06842C2 {
            get {
                return ResourceManager.GetString("AD_Descr_C58336F81569406F91A27916B06842C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy With Stamp.
        /// </summary>
        public static string AD_Descr_D2F31950FB8E4CF3BB048939FCFB833C {
            get {
                return ResourceManager.GetString("AD_Descr_D2F31950FB8E4CF3BB048939FCFB833C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy.
        /// </summary>
        public static string AD_Descr_DF68812F204C4C238C0221C7BA0D91D4 {
            get {
                return ResourceManager.GetString("AD_Descr_DF68812F204C4C238C0221C7BA0D91D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        public static string AD_Descr_E033F356E687498B902F51E698979D8B {
            get {
                return ResourceManager.GetString("AD_Descr_E033F356E687498B902F51E698979D8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AD_Descr_E41FF2180EEC4DDABAB8983D24DE0402 {
            get {
                return ResourceManager.GetString("AD_Descr_E41FF2180EEC4DDABAB8983D24DE0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Print Queue.
        /// </summary>
        public static string AD_Descr_E53A567222294CBCB0F7455EF5579AB9 {
            get {
                return ResourceManager.GetString("AD_Descr_E53A567222294CBCB0F7455EF5579AB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Document.
        /// </summary>
        public static string AD_Descr_E9B70B3FD0BA45EDBB0A2355A690DC53 {
            get {
                return ResourceManager.GetString("AD_Descr_E9B70B3FD0BA45EDBB0A2355A690DC53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tiff As Pdf.
        /// </summary>
        public static string AD_Descr_EADC86BCA4FC46C28BBD7D16F35F1451 {
            get {
                return ResourceManager.GetString("AD_Descr_EADC86BCA4FC46C28BBD7D16F35F1451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string AD_Descr_F5CA112882244041824DFD7CF7EFE39C {
            get {
                return ResourceManager.GetString("AD_Descr_F5CA112882244041824DFD7CF7EFE39C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tiff.
        /// </summary>
        public static string AD_Descr_F8C459039EB5457D82213B16287D93D4 {
            get {
                return ResourceManager.GetString("AD_Descr_F8C459039EB5457D82213B16287D93D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flysheet.
        /// </summary>
        public static string AD_Name_00716D2963C04736BE51D9CACF7A39D8 {
            get {
                return ResourceManager.GetString("AD_Name_00716D2963C04736BE51D9CACF7A39D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email With Insert.
        /// </summary>
        public static string AD_Name_0D678C406DB34580B7F17F3A42D2F60C {
            get {
                return ResourceManager.GetString("AD_Name_0D678C406DB34580B7F17F3A42D2F60C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With FormFill.
        /// </summary>
        public static string AD_Name_0ECB14DC0F01498EA41B136BEC154A7F {
            get {
                return ResourceManager.GetString("AD_Name_0ECB14DC0F01498EA41B136BEC154A7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy With FormFill.
        /// </summary>
        public static string AD_Name_29145036F2A5497897DAC87672EC5194 {
            get {
                return ResourceManager.GetString("AD_Name_29145036F2A5497897DAC87672EC5194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email With Stamp.
        /// </summary>
        public static string AD_Name_326BE88BDB514C4F9A023AB1423F2355 {
            get {
                return ResourceManager.GetString("AD_Name_326BE88BDB514C4F9A023AB1423F2355", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AD_Name_36C0CA04B70F45398FC8AC44714BD622 {
            get {
                return ResourceManager.GetString("AD_Name_36C0CA04B70F45398FC8AC44714BD622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy With Insert.
        /// </summary>
        public static string AD_Name_38A0551356914C92A02D64921AACBB24 {
            get {
                return ResourceManager.GetString("AD_Name_38A0551356914C92A02D64921AACBB24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Insert.
        /// </summary>
        public static string AD_Name_395AC95CCE7D422FBE1A0F29CCA500B1 {
            get {
                return ResourceManager.GetString("AD_Name_395AC95CCE7D422FBE1A0F29CCA500B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Stamp.
        /// </summary>
        public static string AD_Name_3FE333F79178490C83CB66F154480F13 {
            get {
                return ResourceManager.GetString("AD_Name_3FE333F79178490C83CB66F154480F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string AD_Name_4AFC11E6E9924A0F9BDFC0CC42FF9A0B {
            get {
                return ResourceManager.GetString("AD_Name_4AFC11E6E9924A0F9BDFC0CC42FF9A0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string AD_Name_4D1643AE425748EA81B2C2D36F133C1B {
            get {
                return ResourceManager.GetString("AD_Name_4D1643AE425748EA81B2C2D36F133C1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string AD_Name_59FF20A3A7C345A1A267BAD4A3B5219A {
            get {
                return ResourceManager.GetString("AD_Name_59FF20A3A7C345A1A267BAD4A3B5219A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Administration.
        /// </summary>
        public static string AD_Name_673B87A134BF4CE8879F755CB1B2DF02 {
            get {
                return ResourceManager.GetString("AD_Name_673B87A134BF4CE8879F755CB1B2DF02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string AD_Name_6862EA743C6B44F499D1B3DDB4725152 {
            get {
                return ResourceManager.GetString("AD_Name_6862EA743C6B44F499D1B3DDB4725152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string AD_Name_6BA3674F0FD9485986EFAA9BA082A830 {
            get {
                return ResourceManager.GetString("AD_Name_6BA3674F0FD9485986EFAA9BA082A830", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string AD_Name_72F6509C447940D2B708BEAF06F153F8 {
            get {
                return ResourceManager.GetString("AD_Name_72F6509C447940D2B708BEAF06F153F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List .
        /// </summary>
        public static string AD_Name_78FB13B449D5455BAE408CB8BA6B23E7 {
            get {
                return ResourceManager.GetString("AD_Name_78FB13B449D5455BAE408CB8BA6B23E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string AD_Name_803D22369ADB4037A315B542567A9DB3 {
            get {
                return ResourceManager.GetString("AD_Name_803D22369ADB4037A315B542567A9DB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Thumbnail Tiff.
        /// </summary>
        public static string AD_Name_804492E7DBC947EEB3B1C750CC9B427E {
            get {
                return ResourceManager.GetString("AD_Name_804492E7DBC947EEB3B1C750CC9B427E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Management.
        /// </summary>
        public static string AD_Name_97156B7BF78B4F5CAD11D2217732D947 {
            get {
                return ResourceManager.GetString("AD_Name_97156B7BF78B4F5CAD11D2217732D947", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal-detail.
        /// </summary>
        public static string AD_Name_99B76763F2FB45BFAE43854DDED47EF6 {
            get {
                return ResourceManager.GetString("AD_Name_99B76763F2FB45BFAE43854DDED47EF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master-Detail.
        /// </summary>
        public static string AD_Name_AD2B9A7F2AA947C8B744F5CA3CC2032B {
            get {
                return ResourceManager.GetString("AD_Name_AD2B9A7F2AA947C8B744F5CA3CC2032B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AD_Name_B4439FA900564283BAA55CE250312247 {
            get {
                return ResourceManager.GetString("AD_Name_B4439FA900564283BAA55CE250312247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email With FormFill.
        /// </summary>
        public static string AD_Name_C58336F81569406F91A27916B06842C2 {
            get {
                return ResourceManager.GetString("AD_Name_C58336F81569406F91A27916B06842C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy With Stamp.
        /// </summary>
        public static string AD_Name_D2F31950FB8E4CF3BB048939FCFB833C {
            get {
                return ResourceManager.GetString("AD_Name_D2F31950FB8E4CF3BB048939FCFB833C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Copy.
        /// </summary>
        public static string AD_Name_DF68812F204C4C238C0221C7BA0D91D4 {
            get {
                return ResourceManager.GetString("AD_Name_DF68812F204C4C238C0221C7BA0D91D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string AD_Name_E033F356E687498B902F51E698979D8B {
            get {
                return ResourceManager.GetString("AD_Name_E033F356E687498B902F51E698979D8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string AD_Name_E41FF2180EEC4DDABAB8983D24DE0402 {
            get {
                return ResourceManager.GetString("AD_Name_E41FF2180EEC4DDABAB8983D24DE0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Queue.
        /// </summary>
        public static string AD_Name_E53A567222294CBCB0F7455EF5579AB9 {
            get {
                return ResourceManager.GetString("AD_Name_E53A567222294CBCB0F7455EF5579AB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AD_Name_E9B70B3FD0BA45EDBB0A2355A690DC53 {
            get {
                return ResourceManager.GetString("AD_Name_E9B70B3FD0BA45EDBB0A2355A690DC53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tiff As Pdf.
        /// </summary>
        public static string AD_Name_EADC86BCA4FC46C28BBD7D16F35F1451 {
            get {
                return ResourceManager.GetString("AD_Name_EADC86BCA4FC46C28BBD7D16F35F1451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List .
        /// </summary>
        public static string AD_Name_F5CA112882244041824DFD7CF7EFE39C {
            get {
                return ResourceManager.GetString("AD_Name_F5CA112882244041824DFD7CF7EFE39C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tiff.
        /// </summary>
        public static string AD_Name_F8C459039EB5457D82213B16287D93D4 {
            get {
                return ResourceManager.GetString("AD_Name_F8C459039EB5457D82213B16287D93D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is Exactaly the same.
        /// </summary>
        public static string CD_Descr_1 {
            get {
                return ResourceManager.GetString("CD_Descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with the value.
        /// </summary>
        public static string CD_Descr_10 {
            get {
                return ResourceManager.GetString("CD_Descr_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is found within a field.
        /// </summary>
        public static string CD_Descr_2 {
            get {
                return ResourceManager.GetString("CD_Descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Between.
        /// </summary>
        public static string CD_Descr_3 {
            get {
                return ResourceManager.GetString("CD_Descr_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Greater than a value.
        /// </summary>
        public static string CD_Descr_4 {
            get {
                return ResourceManager.GetString("CD_Descr_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than a value.
        /// </summary>
        public static string CD_Descr_5 {
            get {
                return ResourceManager.GetString("CD_Descr_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is Null.
        /// </summary>
        public static string CD_Descr_6 {
            get {
                return ResourceManager.GetString("CD_Descr_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with the Value.
        /// </summary>
        public static string CD_Descr_7 {
            get {
                return ResourceManager.GetString("CD_Descr_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A User&apos;s Information.
        /// </summary>
        public static string CD_Descr_9 {
            get {
                return ResourceManager.GetString("CD_Descr_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string CD_Name_1 {
            get {
                return ResourceManager.GetString("CD_Name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        public static string CD_Name_10 {
            get {
                return ResourceManager.GetString("CD_Name_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string CD_Name_2 {
            get {
                return ResourceManager.GetString("CD_Name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string CD_Name_3 {
            get {
                return ResourceManager.GetString("CD_Name_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string CD_Name_4 {
            get {
                return ResourceManager.GetString("CD_Name_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        public static string CD_Name_5 {
            get {
                return ResourceManager.GetString("CD_Name_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Null.
        /// </summary>
        public static string CD_Name_6 {
            get {
                return ResourceManager.GetString("CD_Name_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        public static string CD_Name_7 {
            get {
                return ResourceManager.GetString("CD_Name_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Value.
        /// </summary>
        public static string CD_Name_9 {
            get {
                return ResourceManager.GetString("CD_Name_9", resourceCulture);
            }
        }
    }
}
