//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MiscRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Lib.MiscRes", typeof(MiscRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login, Invalid User ID or Password, After {0} more time(s) retry, your account will be locked!  REALLY!!!.
        /// </summary>
        public static string Common_Meaning {
            get {
                return ResourceManager.GetString("Common_Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document: {0} not found, Please contact your system Administrator..
        /// </summary>
        public static string Composite_Insert2File {
            get {
                return ResourceManager.GetString("Composite_Insert2File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update by id!.
        /// </summary>
        public static string ErrMsg_FailedUpdateById {
            get {
                return ResourceManager.GetString("ErrMsg_FailedUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Exception_Batch {
            get {
                return ResourceManager.GetString("Exception_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomField.
        /// </summary>
        public static string Exception_CustomField {
            get {
                return ResourceManager.GetString("Exception_CustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id!.
        /// </summary>
        public static string Exception_InvalidId {
            get {
                return ResourceManager.GetString("Exception_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid info ID!.
        /// </summary>
        public static string Exception_InvalidInfoID {
            get {
                return ResourceManager.GetString("Exception_InvalidInfoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        public static string Exception_MethodNotImplemented {
            get {
                return ResourceManager.GetString("Exception_MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Exception_Name {
            get {
                return ResourceManager.GetString("Exception_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create action configuration instance, please contact system administrator!\r\n{0}.
        /// </summary>
        public static string Exception_UnableCreateConfigInstance {
            get {
                return ResourceManager.GetString("Exception_UnableCreateConfigInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong configuration type: {0}.
        /// </summary>
        public static string Exception_WrongConfigurationType {
            get {
                return ResourceManager.GetString("Exception_WrongConfigurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML ID.
        /// </summary>
        public static string Exception_XMLID {
            get {
                return ResourceManager.GetString("Exception_XMLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Info_NotApplicable {
            get {
                return ResourceManager.GetString("Info_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Info_PleaseWait {
            get {
                return ResourceManager.GetString("Info_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Label_Author {
            get {
                return ResourceManager.GetString("Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Label_Author_Desc {
            get {
                return ResourceManager.GetString("Label_Author_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_Description_Desc {
            get {
                return ResourceManager.GetString("Label_Description_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocID.
        /// </summary>
        public static string Label_DocID {
            get {
                return ResourceManager.GetString("Label_DocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocID.
        /// </summary>
        public static string Label_DocID_Desc {
            get {
                return ResourceManager.GetString("Label_DocID_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryDate.
        /// </summary>
        public static string Label_ExpiryDate {
            get {
                return ResourceManager.GetString("Label_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string Label_ExpiryDate_Desc {
            get {
                return ResourceManager.GetString("Label_ExpiryDate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string Label_FileName_Desc {
            get {
                return ResourceManager.GetString("Label_FileName_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSize.
        /// </summary>
        public static string Label_FileSize {
            get {
                return ResourceManager.GetString("Label_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string Label_FileSize_Desc {
            get {
                return ResourceManager.GetString("Label_FileSize_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderID.
        /// </summary>
        public static string Label_FolderID {
            get {
                return ResourceManager.GetString("Label_FolderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderID.
        /// </summary>
        public static string Label_FolderID_Desc {
            get {
                return ResourceManager.GetString("Label_FolderID_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Company.
        /// </summary>
        public static string Label_NewCompany {
            get {
                return ResourceManager.GetString("Label_NewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate.
        /// </summary>
        public static string Label_ReleaseDate {
            get {
                return ResourceManager.GetString("Label_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Label_ReleaseDate_Desc {
            get {
                return ResourceManager.GetString("Label_ReleaseDate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string Label_Shared {
            get {
                return ResourceManager.GetString("Label_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Folder.
        /// </summary>
        public static string Label_SharedFolder {
            get {
                return ResourceManager.GetString("Label_SharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title_Desc {
            get {
                return ResourceManager.GetString("Label_Title_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version_Desc {
            get {
                return ResourceManager.GetString("Label_Version_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructor.
        /// </summary>
        public static string Reflection_DynamicMethodHandlerFactory_CreateConstructor_Constructor {
            get {
                return ResourceManager.GetString("Reflection_DynamicMethodHandlerFactory_CreateConstructor_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not support constructor with parameters.
        /// </summary>
        public static string Reflection_DynamicMethodHandlerFactory_CreateConstructor_NotSupportConstructor {
            get {
                return ResourceManager.GetString("Reflection_DynamicMethodHandlerFactory_CreateConstructor_NotSupportConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field.
        /// </summary>
        public static string Reflection_DynamicMethodHandlerFactory_CreateFieldGetter_Field {
            get {
                return ResourceManager.GetString("Reflection_DynamicMethodHandlerFactory_CreateFieldGetter_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method.
        /// </summary>
        public static string Reflection_DynamicMethodHandlerFactory_CreateMethod_Method {
            get {
                return ResourceManager.GetString("Reflection_DynamicMethodHandlerFactory_CreateMethod_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property: &apos;{0}&apos; of Type: &apos;{1}&apos; does not have a Public Get accessor.
        /// </summary>
        public static string Reflection_DynamicMethodHandlerFactory_CreatePropertyGetter_NoPublicGetAccessor {
            get {
                return ResourceManager.GetString("Reflection_DynamicMethodHandlerFactory_CreatePropertyGetter_NoPublicGetAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        public static string Reflection_DynamicMethodHandlerFactory_CreatePropertyGetter_Property {
            get {
                return ResourceManager.GetString("Reflection_DynamicMethodHandlerFactory_CreatePropertyGetter_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  failed.
        /// </summary>
        public static string Reflection_MethodCaller_CallMethod_Failed {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_CallMethod_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null or empty..
        /// </summary>
        public static string Reflection_MethodCaller_CallPropertyGetter_ArgumentNull {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_CallPropertyGetter_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on Type &apos;{1}&apos; does not have a public getter..
        /// </summary>
        public static string Reflection_MethodCaller_CallPropertyGetter_HasNoPublicGetter {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_CallPropertyGetter_HasNoPublicGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implement default constructor!.
        /// </summary>
        public static string Reflection_MethodCaller_CreateInstance_NotDefaultConstructor {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_CreateInstance_NotDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create instance of Type &apos;{0}&apos;. No public parameterless constructor found..
        /// </summary>
        public static string Reflection_MethodCaller_GetCachedConstructor_CannotCreateInstanceType {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_GetCachedConstructor_CannotCreateInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found field-{0}.
        /// </summary>
        public static string Reflection_MethodCaller_GetCachedField_NotFoundField {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_GetCachedField_NotFoundField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found property-{0}.
        /// </summary>
        public static string Reflection_MethodCaller_GetCachedProperty_NotFoundProperty {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_GetCachedProperty_NotFoundProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to call {0}.
        /// </summary>
        public static string Reflection_MethodCaller_GetPropertyValue_FailedCall {
            get {
                return ResourceManager.GetString("Reflection_MethodCaller_GetPropertyValue_FailedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInfo doesn&apos;t exist in ASP Session..
        /// </summary>
        public static string Security_AppContext_User_UserInfoNoExist {
            get {
                return ResourceManager.GetString("Security_AppContext_User_UserInfoNoExist", resourceCulture);
            }
        }
    }
}
