//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doxim.L10N.Js {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doxim.L10N.Resources.Js.JsRes", typeof(JsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is one of {0}&apos;s default action. \n\r Please change {0} default action first!.
        /// </summary>
        public static string Admin_Action_ActionProfileView_DefaultAction {
            get {
                return ResourceManager.GetString("Admin_Action_ActionProfileView_DefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document type.
        /// </summary>
        public static string Admin_Action_ActionProfileView_DocumentType {
            get {
                return ResourceManager.GetString("Admin_Action_ActionProfileView_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Name\&quot; field..
        /// </summary>
        public static string Admin_Action_ActionProfileView_FieldEmpty {
            get {
                return ResourceManager.GetString("Admin_Action_ActionProfileView_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio.
        /// </summary>
        public static string Admin_Action_ActionProfileView_Portfolio {
            get {
                return ResourceManager.GetString("Admin_Action_ActionProfileView_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string Admin_Action_ActionProfileView_View {
            get {
                return ResourceManager.GetString("Admin_Action_ActionProfileView_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address can&apos;t be empty!.
        /// </summary>
        public static string Admin_Action_EmailConfigControl_Empty {
            get {
                return ResourceManager.GetString("Admin_Action_EmailConfigControl_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when select current setting and user not changeable must input a valid email address.
        /// </summary>
        public static string Admin_Action_EmailConfigControl_Invalid {
            get {
                return ResourceManager.GetString("Admin_Action_EmailConfigControl_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias: {0} appear more than once!.
        /// </summary>
        public static string Admin_Action_FieldsConfigControl_Alias {
            get {
                return ResourceManager.GetString("Admin_Action_FieldsConfigControl_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select at least one field.
        /// </summary>
        public static string Admin_Action_FieldsConfigControl_FieldEmpty {
            get {
                return ResourceManager.GetString("Admin_Action_FieldsConfigControl_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List fields cannot be empty.
        /// </summary>
        public static string Admin_Action_FieldsConfigControl_ListEmpty {
            get {
                return ResourceManager.GetString("Admin_Action_FieldsConfigControl_ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file selection type: Basic/Associated..
        /// </summary>
        public static string Admin_Action_FileSelectionConfigControl_SelectType {
            get {
                return ResourceManager.GetString("Admin_Action_FileSelectionConfigControl_SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value from the dropdown list..
        /// </summary>
        public static string Admin_Action_FileSelectionConfigControl_SelectValue {
            get {
                return ResourceManager.GetString("Admin_Action_FileSelectionConfigControl_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a constrain type for converting..
        /// </summary>
        public static string Admin_Action_ImageConvert_ConstrainType {
            get {
                return ResourceManager.GetString("Admin_Action_ImageConvert_ConstrainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enPlease enter a valid value for Height field(1-2000).
        /// </summary>
        public static string Admin_Action_ImageConvert_Height {
            get {
                return ResourceManager.GetString("Admin_Action_ImageConvert_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enPlease enter a valid value for Width field(1-2000).
        /// </summary>
        public static string Admin_Action_ImageConvert_Width {
            get {
                return ResourceManager.GetString("Admin_Action_ImageConvert_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Insert Position.
        /// </summary>
        public static string Admin_Action_InsertConfigControl_SelectInsert {
            get {
                return ResourceManager.GetString("Admin_Action_InsertConfigControl_SelectInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select detail action.
        /// </summary>
        public static string Admin_Action_MasterDetailConfigControl_SelectDetailAction {
            get {
                return ResourceManager.GetString("Admin_Action_MasterDetailConfigControl_SelectDetailAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Detail View.
        /// </summary>
        public static string Admin_Action_MasterDetailConfigControl_SelectDetailView {
            get {
                return ResourceManager.GetString("Admin_Action_MasterDetailConfigControl_SelectDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select master action.
        /// </summary>
        public static string Admin_Action_MasterDetailConfigControl_SelectMasterAction {
            get {
                return ResourceManager.GetString("Admin_Action_MasterDetailConfigControl_SelectMasterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input integer for the \&quot;Order\&quot; field.
        /// </summary>
        public static string Admin_Action_PortfolioViewsControl_OrderField {
            get {
                return ResourceManager.GetString("Admin_Action_PortfolioViewsControl_OrderField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input integer for the \&quot;Value\&quot; field..
        /// </summary>
        public static string Admin_Action_PortfolioViewsControl_ValueField {
            get {
                return ResourceManager.GetString("Admin_Action_PortfolioViewsControl_ValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one stamp showing page.
        /// </summary>
        public static string Admin_Action_StampConfigControl_OneStamp {
            get {
                return ResourceManager.GetString("Admin_Action_StampConfigControl_OneStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Underlay/Overlay stamp.
        /// </summary>
        public static string Admin_Action_StampConfigControl_OverlayStamp {
            get {
                return ResourceManager.GetString("Admin_Action_StampConfigControl_OverlayStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure.
        /// </summary>
        public static string Admin_Action_WorkFlowControl_Configure {
            get {
                return ResourceManager.GetString("Admin_Action_WorkFlowControl_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid currency number.
        /// </summary>
        public static string Admin_Action_WorkFlowControl_EnterCurrency {
            get {
                return ResourceManager.GetString("Admin_Action_WorkFlowControl_EnterCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date value for the field with format: YYYY-MM-DD..
        /// </summary>
        public static string Admin_Action_WorkFlowControl_EnterDate {
            get {
                return ResourceManager.GetString("Admin_Action_WorkFlowControl_EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid integer number (?,147,483,648 to 2,147,483,647).
        /// </summary>
        public static string Admin_Action_WorkFlowControl_EnterInteger {
            get {
                return ResourceManager.GetString("Admin_Action_WorkFlowControl_EnterInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or input From To Do Status.
        /// </summary>
        public static string Admin_Action_WorkFlowControl_ToDoStatus {
            get {
                return ResourceManager.GetString("Admin_Action_WorkFlowControl_ToDoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflow can not be empty.
        /// </summary>
        public static string Admin_Action_WorkFlowControl_WorkflowEmpty {
            get {
                return ResourceManager.GetString("Admin_Action_WorkFlowControl_WorkflowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Batch Name\&quot; field..
        /// </summary>
        public static string Admin_Batch_BatchProfileView_BatchName {
            get {
                return ResourceManager.GetString("Admin_Batch_BatchProfileView_BatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value for the \&quot;Date Active\&quot; field..
        /// </summary>
        public static string Admin_Batch_BatchProfileView_DateActive {
            get {
                return ResourceManager.GetString("Admin_Batch_BatchProfileView_DateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value for the \&quot;Date Expire\&quot; field..
        /// </summary>
        public static string Admin_Batch_BatchProfileView_DateExpire {
            get {
                return ResourceManager.GetString("Admin_Batch_BatchProfileView_DateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The expiry date is previous to active date. \r\nDo you want continue?.
        /// </summary>
        public static string Admin_Batch_BatchProfileView_ExpiryDateWarning {
            get {
                return ResourceManager.GetString("Admin_Batch_BatchProfileView_ExpiryDateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Company Name\&quot; field..
        /// </summary>
        public static string Admin_Company_CompanyProfileGeneralView_EnterValue {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileGeneralView_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid \&quot;Post Code\&quot; field. Please re-enter..
        /// </summary>
        public static string Admin_Company_CompanyProfileGeneralView_InvalidField {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileGeneralView_InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback email body cannot exceed 900 characters!.
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_EmailBody {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback email can not empty!.
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_EmailEmpty {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of 8 characters is required..
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_Minimum8 {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_Minimum8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of 8 characters and a combination of both alpha and numeric characters are required..
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_Minimum8Alpha {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_Minimum8Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Requirement.
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_NoRequirement {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_NoRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback subject can not empty!.
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_SubjectEmpty {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_SubjectEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback ulr can not be empty!.
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_UrlEmpty {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_UrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback url should start with \&quot;http://\&quot; or \&quot;https://\&quot;.
        /// </summary>
        public static string Admin_Company_CompanyProfileSettingView_UrlStartWith {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileSettingView_UrlStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the right to delete the company:{0}.\n\r.
        /// </summary>
        public static string Admin_Company_CompanyProfileView_NoRight {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileView_NoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Cannot delete the company: {0}.\n\r Please delete the following related objects first:\n\r--.
        /// </summary>
        public static string Admin_Company_CompanyProfileView_Warning {
            get {
                return ResourceManager.GetString("Admin_Company_CompanyProfileView_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search value can not be empty.
        /// </summary>
        public static string Admin_Company_UserListView_ValueEmpty {
            get {
                return ResourceManager.GetString("Admin_Company_UserListView_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Name\&quot;.
        /// </summary>
        public static string Admin_CustomField_CustomFieldGeneralView_Name {
            get {
                return ResourceManager.GetString("Admin_CustomField_CustomFieldGeneralView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid order number..
        /// </summary>
        public static string Admin_CustomField_CustomFieldValuesView_OrderNo {
            get {
                return ResourceManager.GetString("Admin_CustomField_CustomFieldValuesView_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} appear more than once!.
        /// </summary>
        public static string Admin_CustomField_CustomFieldValuesView_Value {
            get {
                return ResourceManager.GetString("Admin_CustomField_CustomFieldValuesView_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search value can not be empty!.
        /// </summary>
        public static string Admin_DocType_DocumentTypeBatchListView_ValueEmpty {
            get {
                return ResourceManager.GetString("Admin_DocType_DocumentTypeBatchListView_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type: {0}.
        /// </summary>
        public static string Admin_DocType_DocumentTypeGeneralView_DocumentType {
            get {
                return ResourceManager.GetString("Admin_DocType_DocumentTypeGeneralView_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid number in the \&quot;Expire Years\&quot; field..
        /// </summary>
        public static string Admin_DocType_DocumentTypeGeneralView_InvalidExpireYears {
            get {
                return ResourceManager.GetString("Admin_DocType_DocumentTypeGeneralView_InvalidExpireYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Cannot delete the document type: {0}.\n\r Please delete the following related objects first:.
        /// </summary>
        public static string Admin_DocType_DocumentTypeGeneralView_RelatedObject {
            get {
                return ResourceManager.GetString("Admin_DocType_DocumentTypeGeneralView_RelatedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only CAD can delete folder!.
        /// </summary>
        public static string Admin_Folder_FolderGeneralView_CADOnly {
            get {
                return ResourceManager.GetString("Admin_Folder_FolderGeneralView_CADOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Folder Name\&quot; field..
        /// </summary>
        public static string Admin_Folder_FolderGeneralView_FolderNameEmpty {
            get {
                return ResourceManager.GetString("Admin_Folder_FolderGeneralView_FolderNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input criteria value!.
        /// </summary>
        public static string Admin_Group_GroupGeneralView_CriteriaValue {
            get {
                return ResourceManager.GetString("Admin_Group_GroupGeneralView_CriteriaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select custom field!.
        /// </summary>
        public static string Admin_Group_GroupGeneralView_CustomField {
            get {
                return ResourceManager.GetString("Admin_Group_GroupGeneralView_CustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} users from current group?.
        /// </summary>
        public static string Admin_Group_GroupManualView_Confirm {
            get {
                return ResourceManager.GetString("Admin_Group_GroupManualView_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the user(s) you want to remove first!.
        /// </summary>
        public static string Admin_Group_GroupManualView_SelectUser {
            get {
                return ResourceManager.GetString("Admin_Group_GroupManualView_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metatag is referenced by documents, can not be delete!.
        /// </summary>
        public static string Admin_MetaTag_MetaTagGeneralView_DeleteFail {
            get {
                return ResourceManager.GetString("Admin_MetaTag_MetaTagGeneralView_DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the right to delete the organization: {0}.
        /// </summary>
        public static string Admin_Organization_OrganizationProfileView_DeleteTheOrganization {
            get {
                return ResourceManager.GetString("Admin_Organization_OrganizationProfileView_DeleteTheOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use [[CustomField.FieldName]] or [[CommonField.FieldName]] format!.
        /// </summary>
        public static string Admin_Portfolio_PortfolioGeneralView_Format {
            get {
                return ResourceManager.GetString("Admin_Portfolio_PortfolioGeneralView_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Portfolio Name\&quot; field..
        /// </summary>
        public static string Admin_Portfolio_PortfolioGeneralView_PortfolioName {
            get {
                return ResourceManager.GetString("Admin_Portfolio_PortfolioGeneralView_PortfolioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to save?.
        /// </summary>
        public static string Admin_Portfolio_PortfolioGeneralView_SaveConfirm {
            get {
                return ResourceManager.GetString("Admin_Portfolio_PortfolioGeneralView_SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Common Field Name\&quot; field..
        /// </summary>
        public static string Admin_PortfolioField_PortfolioFieldView_CommonFieldName {
            get {
                return ResourceManager.GetString("Admin_PortfolioField_PortfolioFieldView_CommonFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for the \&quot;Field Name\&quot; field..
        /// </summary>
        public static string Admin_PortfolioField_PortfolioFieldView_FieldName {
            get {
                return ResourceManager.GetString("Admin_PortfolioField_PortfolioFieldView_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one row will be deleted, Are you sure?.
        /// </summary>
        public static string Admin_User_UserProfileCustomFieldView_Confirm {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileCustomFieldView_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all of items will be deleted, Are you sure?.
        /// </summary>
        public static string Admin_User_UserProfileCustomFieldView_ConfirmAllItem {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileCustomFieldView_ConfirmAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the required field.
        /// </summary>
        public static string Admin_User_UserProfileCustomFieldView_EnterRequiredField {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileCustomFieldView_EnterRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;First Name\&quot; or \&quot;Last Name\&quot; field..
        /// </summary>
        public static string Admin_User_UserProfileGeneralView_FirstNameLastName {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileGeneralView_FirstNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid character(s) in the \&quot;User ID\&quot; field.\n Valid characters in a-z,A-Z,0-9 or + - _ ..
        /// </summary>
        public static string Admin_User_UserProfileGeneralView_InvalidUserID {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileGeneralView_InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;User ID\&quot; field..
        /// </summary>
        public static string Admin_User_UserProfileGeneralView_UserID {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileGeneralView_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Portfolio!.
        /// </summary>
        public static string Admin_User_UserProfileSettingView_Portfolio {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileSettingView_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user setting.
        /// </summary>
        public static string Admin_User_UserProfileSettingView_Setting {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileSettingView_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select View!.
        /// </summary>
        public static string Admin_User_UserProfileSettingView_View {
            get {
                return ResourceManager.GetString("Admin_User_UserProfileSettingView_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid boolean value (Yes/No;True/False;1/0).
        /// </summary>
        public static string Admin_View_ViewDetailView_EnterBoolean {
            get {
                return ResourceManager.GetString("Admin_View_ViewDetailView_EnterBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Value can not be empty.
        /// </summary>
        public static string Admin_View_ViewDetailView_UserValueEmpty {
            get {
                return ResourceManager.GetString("Admin_View_ViewDetailView_UserValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can not be empty.
        /// </summary>
        public static string Admin_View_ViewDetailView_ValueEmpty {
            get {
                return ResourceManager.GetString("Admin_View_ViewDetailView_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for the \&quot;Document Type\&quot; field.
        /// </summary>
        public static string Admin_View_ViewGeneralView_DocumentType {
            get {
                return ResourceManager.GetString("Admin_View_ViewGeneralView_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;View Name\&quot; field.
        /// </summary>
        public static string Admin_View_ViewGeneralView_ViewName {
            get {
                return ResourceManager.GetString("Admin_View_ViewGeneralView_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search criteria can not be empty!.
        /// </summary>
        public static string Common_Control_AdvancedSearchView_CriteriaEmpty {
            get {
                return ResourceManager.GetString("Common_Control_AdvancedSearchView_CriteriaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file selection type: Basic/Associated..
        /// </summary>
        public static string Common_Control_ConfigurationClass_SelecType {
            get {
                return ResourceManager.GetString("Common_Control_ConfigurationClass_SelecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value from the dropdown list..
        /// </summary>
        public static string Common_Control_ConfigurationClass_SelecValue {
            get {
                return ResourceManager.GetString("Common_Control_ConfigurationClass_SelecValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        public static string Common_Control_DocEditView_FileName {
            get {
                return ResourceManager.GetString("Common_Control_DocEditView_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a document type.
        /// </summary>
        public static string Common_Control_DocEditView_SelectDocType {
            get {
                return ResourceManager.GetString("Common_Control_DocEditView_SelectDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file!.
        /// </summary>
        public static string Common_Control_DocEditView_SelectFile {
            get {
                return ResourceManager.GetString("Common_Control_DocEditView_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file NOT more than 50MB in file size; Check in process will fail if uploading file takes more than 1 hour upon your internet connection!.
        /// </summary>
        public static string Common_Control_DocEditView_SelectFileMsg {
            get {
                return ResourceManager.GetString("Common_Control_DocEditView_SelectFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 $2 will be deleted, Are you sure?.
        /// </summary>
        public static string Common_DoximGrid_Confirm {
            get {
                return ResourceManager.GetString("Common_DoximGrid_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enPlease select rows to delete!.
        /// </summary>
        public static string Common_DoximGrid_DeleteRow {
            get {
                return ResourceManager.GetString("Common_DoximGrid_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid window style! $1.
        /// </summary>
        public static string Common_Lib_CenterWindow_InvalidStyle {
            get {
                return ResourceManager.GetString("Common_Lib_CenterWindow_InvalidStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to DELETE this $1 ?.
        /// </summary>
        public static string Common_Lib_ConfirmDelete_Confirm {
            get {
                return ResourceManager.GetString("Common_Lib_ConfirmDelete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete:\r\nThere are sub-folder(s) under this folder..
        /// </summary>
        public static string Common_Lib_ConfirmDeleteSub_CannotDelete {
            get {
                return ResourceManager.GetString("Common_Lib_ConfirmDeleteSub_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid onConfirm!.
        /// </summary>
        public static string Common_Lib_CreateConfirmWindow_InvalidConfirm {
            get {
                return ResourceManager.GetString("Common_Lib_CreateConfirmWindow_InvalidConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Your browser does not support AJAX.
        /// </summary>
        public static string Common_Lib_CreateRequestObject_AjaxError {
            get {
                return ResourceManager.GetString("Common_Lib_CreateRequestObject_AjaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string Common_Lib_IsValidEmail_InvalidEmail {
            get {
                return ResourceManager.GetString("Common_Lib_IsValidEmail_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found in the Doc IFrame.
        /// </summary>
        public static string Common_Lib_ReinitIframeDocument_DocError {
            get {
                return ResourceManager.GetString("Common_Lib_ReinitIframeDocument_DocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found in the Master IFrame.
        /// </summary>
        public static string Common_Lib_ReinitMasterIframe_MasterError {
            get {
                return ResourceManager.GetString("Common_Lib_ReinitMasterIframe_MasterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Common_Lib_ShowProgressPercentInfo_Progress {
            get {
                return ResourceManager.GetString("Common_Lib_ShowProgressPercentInfo_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords entered are not identical,press OK to continue!.
        /// </summary>
        public static string Common_Lib_ValidatePassword_NotIdentical {
            get {
                return ResourceManager.GetString("Common_Lib_ValidatePassword_NotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Password\&quot; field..
        /// </summary>
        public static string Common_Lib_ValidatePassword_PasswordEmpty {
            get {
                return ResourceManager.GetString("Common_Lib_ValidatePassword_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s password is set to a standard rule, a minimum of 8 characters is required! \n Please click OK, re-enter your password..
        /// </summary>
        public static string Common_Lib_ValidatePassword_StandardRule {
            get {
                return ResourceManager.GetString("Common_Lib_ValidatePassword_StandardRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s password is set to a strong rule, a minimum of 8 characters and a combination of both alpha and numeric characters are required! Please click OK, re-enter your password..
        /// </summary>
        public static string Common_Lib_ValidatePassword_StrongRule {
            get {
                return ResourceManager.GetString("Common_Lib_ValidatePassword_StrongRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No member selected, please select member to continue.
        /// </summary>
        public static string Common_MemberSelector_SelectMember {
            get {
                return ResourceManager.GetString("Common_MemberSelector_SelectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find element $1 !.
        /// </summary>
        public static string Common_Validation_ElementNotFound {
            get {
                return ResourceManager.GetString("Common_Validation_ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid!.
        /// </summary>
        public static string Label_Invalid {
            get {
                return ResourceManager.GetString("Label_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid character(s) in the \&quot;XML ID\&quot; field.\n Valid characters in a-z,A-Z,0-9..
        /// </summary>
        public static string Label_InvalidCharInXMLID {
            get {
                return ResourceManager.GetString("Label_InvalidCharInXMLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create {0} : {1}.
        /// </summary>
        public static string Label_PleaseCreate {
            get {
                return ResourceManager.GetString("Label_PleaseCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;XML ID\&quot; field..
        /// </summary>
        public static string Label_XMLIDEmpty {
            get {
                return ResourceManager.GetString("Label_XMLIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can\&apos;t start with number in the \&quot;XML ID\&quot; field.
        /// </summary>
        public static string Label_XMLIDStartWithNo {
            get {
                return ResourceManager.GetString("Label_XMLIDStartWithNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered {0} characters. The system only allows max 2000 characters.
        /// </summary>
        public static string Web_Doc_DocNoteView_Maximum {
            get {
                return ResourceManager.GetString("Web_Doc_DocNoteView_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for the \&quot;Folder Name\&quot; field..
        /// </summary>
        public static string Web_Folder_FolderProfileView_EnterValue {
            get {
                return ResourceManager.GetString("Web_Folder_FolderProfileView_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID and password must not empty.
        /// </summary>
        public static string Web_LoginView_UserIDEmpty {
            get {
                return ResourceManager.GetString("Web_LoginView_UserIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one search field value..
        /// </summary>
        public static string Web_Portfolio_PortfolioViewsListView_EnterValue {
            get {
                return ResourceManager.GetString("Web_Portfolio_PortfolioViewsListView_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to release the print job?.
        /// </summary>
        public static string Web_PrintQueue_Job_PrintJobView_PrintJob {
            get {
                return ResourceManager.GetString("Web_PrintQueue_Job_PrintJobView_PrintJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid new password! New password should not be same as old password!.
        /// </summary>
        public static string Web_User_MyProfilePasswordView_InvalidPassword {
            get {
                return ResourceManager.GetString("Web_User_MyProfilePasswordView_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid url!.
        /// </summary>
        public static string Web_User_TreeNode_InvalidUrl {
            get {
                return ResourceManager.GetString("Web_User_TreeNode_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double click icon to refresh child nodes.
        /// </summary>
        public static string Web_User_TreeNode_Refresh {
            get {
                return ResourceManager.GetString("Web_User_TreeNode_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session time out, please login again..
        /// </summary>
        public static string Web_User_TreeNode_Timeout {
            get {
                return ResourceManager.GetString("Web_User_TreeNode_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many nodes retrieved, please contact administrator!.
        /// </summary>
        public static string Web_User_TreeView_Nodes {
            get {
                return ResourceManager.GetString("Web_User_TreeView_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid date part format: $1.
        /// </summary>
        public static string Web_View_View_Date {
            get {
                return ResourceManager.GetString("Web_View_View_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid date part format for Ends With: $1.
        /// </summary>
        public static string Web_View_View_EndsWith {
            get {
                return ResourceManager.GetString("Web_View_View_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Now&apos; keyword must be used like this: Now + [or -] number.
        /// </summary>
        public static string Web_View_View_Now {
            get {
                return ResourceManager.GetString("Web_View_View_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid date part format for Starts With: $1.
        /// </summary>
        public static string Web_View_View_StartsWith {
            get {
                return ResourceManager.GetString("Web_View_View_StartsWith", resourceCulture);
            }
        }
    }
}
